### ISSUE TITLE
Alternative for Firefox Theme

### ISSUE THREAD

**Issue by francoism90** [NicoHood/arc-theme#107]
### Checks

*Ensure you...*

- **Really** read the list above and checked if your issue is or not duplicated.
- **Really** read the README and there is nothing about your issue.
- **Really** checked if the theme is installed or built specifically for the GTK+ 3/distribution version you're using.

### Details

- Distribution (with version): Arch Linux
  - Base distribution (if have, with version): 19.08.18
- Desktop environment (with version): KDE 5.13
- Arc version/commit (don't put "latest"): https://github.com/NicoHood/arc-theme/commit/4149a7d0881919befbcd5455268c5cff8418e648
- GTK+ 3 version: 3.22.30-1
  - Murrine engine version: 0.98.2-3
  - `gnome-themes-standard` version: 3.28-1
- Installation method (package or source): package

I just want to point out that some colors don't apply to Firefox without using a theme. Unfortunately the upstream theme hasn't been updated in a long time. As an alternative you may want to use [Firefox Color](https://color.firefox.com/?theme=XQAAAALsAAAAAAAAAABBqYhm849SCiazH1KEGccwS-xNVAWBvB94sLB6_ObzDAu7F4lSaIRlSbSrYzs7eDzpWr-pM9m8IUL5oVNFntCW7Gp0sbvr3Hf3GSF7_6hfVkE_MNVyDOtGKwu7soiSC21pQalwLQBBQrnjod0SKd5g0yhIP-3YUnm1YxjnOOkUNbXhZr1jUhwdVeqmt-f8NIa0E_ZTagRoSbgWotLvkYnOTNSB__6j3AA), although not a full alternative, it may help help matching colors, even for some using the dark theme.

Thanks for keeping this up-to-date, and if needed I'll close this issue. :)

**Comment by NicoHood** [comment]
I am also using firefox, but I dont understand the problem. What should we change? For me everything works correct, I guess you mean some smaller menus are not 100% arc?

Feel free to open a PR for better firefox colors.

**Comment by francoism90** [comment]
@NicoHood Sorry, I need this in KDE, for some reason not all colors are applied the FF interface. If this is an issue on my end, I'll close this one. :)

**Comment by NicoHood** [comment]
I dont know. A Screenshot would help to understand better.

**Comment by francoism90** [comment]
@NicoHood It only works when using FF and having the color-extension installed. I'll try to add more info if needed, but for now I'll leave it as it is.
