### ISSUE TITLE
Request: Arc "darkest" version

### ISSUE THREAD

**Issue by geplus** [NicoHood/arc-theme#11]
Hi,
can you add a variant of the arc-darker theme, with the menu background having the dark color (as it happens on the numix theme)? For certain types of icon themes, like the evolvere icon theme this is recommended, if you want to use them without a full dark theme.
Thanks in advance

**Comment by fossfreedom** [comment]
Happy for anyone to have a go and submit a pull-request with the changes.

**Comment by NicoHood** [comment]
Which menu background? Can you take a screenshot of arc and a working theme?

**Comment by geplus** [comment]
![00001](https://user-images.githubusercontent.com/5302281/34062961-411616b2-e1e7-11e7-9a82-ab264e70cefb.png)
![00002](https://user-images.githubusercontent.com/5302281/34062973-49af622e-e1e7-11e7-9ea9-d20946abede4.png)

This is from my custom arc theme, called ArcMix.
I have not enough skills and time for pubic it on github,so please use this gtk.css for see the modifications I've made for the menus background (requires gtk 3.20 or above):

https://gist.github.com/geplus/b6b5a342384215e37e035cc75ad6d150

Anyone who is interested to use or fork this gtk.css, is welcome, and please, in this case let me know

**Comment by geplus** [comment]
![0004](https://user-images.githubusercontent.com/5302281/34063477-45d5eb70-e1ea-11e7-9707-70051c9dcd5a.png)
![0005](https://user-images.githubusercontent.com/5302281/34063496-5a2c2030-e1ea-11e7-894f-e5355dfff0a8.png)

And this is the arc darker variant theme

**Comment by NicoHood** [comment]
So you mean the menus in "File", "Edit" etc? Those are dark for me, but you have to enable the global dark theme (in gnome tweaks for example).

Arc-darker + global dark theme -> black menus
arc-dark no global dark theme -> black menus

Should be fine, why should we fix something here? Maybe this is a bug for your DE? I have tested gnome, which DE are you using?

**Comment by geplus** [comment]
I use xfce, how I can enable the global dark theme in xfce?

**Comment by NicoHood** [comment]
You can use gnome tweak tool also in xfce. There is no other way to do it with xfce tools as far as i know.
However this is a bug, we dont need a theme variant. On the dark theme those menus should be dark.

**Comment by geplus** [comment]
The arc theme version I've used in the screenshots is from the arc-solid-darker theme. I tested also your latest git of the file gtk-solid-darker.css , and it gives the same result on my system; so, my request was about an arc-darker modification with dark colored menus.

However, I think a theme should work in a certain way without any exernal tool.

**Comment by NicoHood** [comment]
Then you should enable the global dark theme or use arc-dark directly.

**Comment by geplus** [comment]
My request on this issue was clear: a version of the arc-darker theme that have also dark menus by default, as the numix theme do.
I don't like full-dark themes, so I won't use the arc-dark theme.
If you are interested to try to develop this, I'll say you thank you.
If not, this issue can be considered closed.
Thank you for your attention and thank you for continuing the arc theme's developement.

**Comment by fossfreedom** [comment]
thanks.  This is not in scope, therefore this issue is closed.

**Comment by NicoHood** [comment]
Yes, you have some options. I think its good as it is unless other users also suggest this change. Thanks for the idea though :)
