### ISSUE TITLE
Firefox - horizontal separators not showing

### ISSUE THREAD

**Issue by 1earch** [NicoHood/arc-theme#114]
Hi!

Since a while, on Firefox, I could not see my bookmark separators in folders.
Recently, I found this too annoying and tried to figured out why.

According to the [Issue 526 of horst3180/arc-theme](https://github.com/horst3180/arc-theme/issues/526), the menu separators where modified because too ugly. At that time, Firefox just began to use GTK3 and that's why it was ugly.

However, now, I tried the default gnome theme (Adwaita) and the render of these separators was good :smile: 

So I tried to remove the code put by this commit in the CSS file and the result was pretty in my mind (separators OK + arc-theme).

Could you revert [this commit](https://github.com/horst3180/arc-theme/commit/8f25fc712ea2da1ce13c30417269b4b1d0055f25) ?

### Details

- Distribution: Arch Linux, fully updated as of 31/08/2018
  - Base distribution: N/A
- Desktop environment: i3 version 4.15.0.1
- Arc version/commit: 20180715
- GTK+ 3 version: 3.22.30
  - Murrine engine version: 0.98.2
  - `gnome-themes-standard` version: 3.28 (`gnome-themes-extra` on Arch Linux)
- Installation method (package or source): [arc-gtk-theme package](https://www.archlinux.org/packages/community/any/arc-gtk-theme/) from `community` repository via pacman

**Comment by NicoHood** [comment]
Please provide us with screenshots, so we can decider better :)

**Comment by 1earch** [comment]
Sorry, I didn't think about screenshots ^^

### Folder separator (before)
![before_folder](https://user-images.githubusercontent.com/1888635/44923918-f8038c00-ad49-11e8-9706-5c3d19ea90b5.jpg)

### Folder separator (after)
![after_folder](https://user-images.githubusercontent.com/1888635/44923916-f76af580-ad49-11e8-929a-e3bd52f78e34.jpg)

### Menu separator (before)
![before_menu](https://user-images.githubusercontent.com/1888635/44923920-f8038c00-ad49-11e8-9969-c5e3da3d0898.jpg)

### Menu separator (after)
![after_menu](https://user-images.githubusercontent.com/1888635/44923917-f76af580-ad49-11e8-8b12-aaf0979b58e9.jpg)

**Comment by NicoHood** [comment]
Okay that looks better. Could you please prepare a PR?
