### ISSUE TITLE
Arc Gnome Shell Theme Black Artifacting

### ISSUE THREAD

**Issue by AtomRidge** [NicoHood/arc-theme#119]
![arc theme artifacting1](https://user-images.githubusercontent.com/34950324/45310634-57b22200-b516-11e8-8e99-29c360529ca5.png)

All of the GNOME Shell themes that come with the Arc theme have black artifacting around the status menu and application name whenever an app is not used in full screen. This issue seems to be specific to Fedora, as this doesn't seem to occur in Ubuntu or Arch.

Distribution: Fedora 29
DE: GNOME Shell
Arc Theme version: 20170302-9.fc28 (installed from Fedora repos)
GTK+ version: 3.22
Murrine Engine version: 0.98.2-14.fc28
gnome-themes-extras version: 3.28-1.fc28
Installation Method: Package, from official Fedora repos

**Comment by fossfreedom** [comment]
Please can you try the latest stable version in this repo please? 

Also please can you prod your fedora maintainer to update arc theme to the latest available.

**Comment by AtomRidge** [comment]
@fossfreedom The version I am using is currently the latest available in the Fedora repos. Also, on https://apps.fedoraproject.org/packages/arc-theme/ there is already a bug request to use this repo instead of the unmaintained one by horst3180 . I'm not really sure how to contact maintainers directly, however.

**Comment by fossfreedom** [comment]
K. You will need to install the updated theme manually then. Instructions on how to compile are in the readme.

**Comment by AtomRidge** [comment]
Thanks! Installing from source fixed the issue.
