### ISSUE TITLE
Push your soft fork for our variation in our repo 

### ISSUE THREAD

**Issue by Ste74** [NicoHood/arc-theme#12]
First of all thank you for this .. i have just now pushed in our repo your work .. only a note in my version i removed all old gtk version and only build >= gtk3.20 

https://github.com/manjaro/packages-community/commit/2bedcb5ea795e1b4db0e7299d950b0b2f4b12072

**Comment by NicoHood** [comment]
@Ste74 Is there any reason why you removed the older versions? Cant they just coexist? If you have any noteable change, feel free to open a PR for that.

**Comment by Ste74** [comment]
I have build for Manjaro and Manjaro/Arch not use old gtk version.. but also to decrease the build time.. my version change all blueish color with maia and breath variation so re-color all asset need time 😉

**Comment by NicoHood** [comment]
Wouldnt it be possible for you to integrate the color changes to this fork/upstream? This would make your build simpler and others have the change to use this theme too. It would be nice if you can post a screenshot of the manjaro arc theme version.

**Comment by Ste74** [comment]
Yep.. what you mean? Create a script bash to change the color or integrate properly in the source ?

**Comment by NicoHood** [comment]
Integrate properly in the source of course.

**Comment by NicoHood** [comment]
Found screenshots here:

![](https://forum.manjaro.org/uploads/default/original/2X/1/1c9f07cacc8ccc9ea519455ad5f874d4b5272e7c.jpg)

![](https://forum.manjaro.org/uploads/default/original/2X/1/13e7d5934338843ae535e6a69a4d8b546d7c426e.jpg)

Looks nice. If we can have a simple integration to change some colors for the arc theme, that'd be really nice.

**Comment by NicoHood** [comment]
Maybe @mclmza from https://github.com/mclmza/arc-theme-Red is also interested in integrating fixes for multiple colors. It should be generic enough that we do not need to test all variants.

@fossfreedom any opinions?

**Comment by NicoHood** [comment]
Isnt it enough to change the colors here? https://github.com/NicoHood/arc-theme/blob/master/common/gtk-3.0/3.20/sass/_colors.scss

**Comment by fossfreedom** [comment]
Certainly a very good idea if this way of collaborative way of working can be encouraged.   Better community involvement and ownership. 

For example have a scripts subfolder called custom and in there have a maia or red script that just sed  the changes.

Then a makefile change with --custom=maia to run that script

To make this viable will need a change from gulp to sassc to compile the css as part of the make.

**Comment by Ste74** [comment]
This is good.. Letto me know What you need.. My pkgbuild already use sed to change all blueish color to maia.. Let me extract This part.. ( i m not At home now and fight with My Smartphone to write in English lol)

**Comment by mclmza** [comment]
@NicoHood @Ste74 Yes, I would be very interested.

**Comment by fossfreedom** [comment]
@Ste74 and @mclmza 

  I've pushed to the sassc branch the ability to compile the theme when you do an autogen.sh and sudo make install i.e. you no longer have to use npm/nvm and gulp to compile.  Just install the new dependency sassc

 What needs now to be done is to add the ability to run your bash script that customised your version of the theme.  As I mentioned above I would envisage that you would run (for example) ./autogen.sh --with-custom=maia which would then run "maia.sh" in a new subfolder called custom

**Comment by NicoHood** [comment]
Switching to sassc sounds like a good idea in general. Can we please open a PR for that to already test this change?

**Comment by Ste74** [comment]
Well , sorry for delay.. i'm little busy in this time, i can try this branch after friday  ;)

**Comment by NicoHood** [comment]
@Ste74 @mclmza Feel free to play with the new sassc compilation. You can find the current RC here:
https://github.com/NicoHood/arc-theme/pull/22

**Comment by Ste74** [comment]
@NicoHood , @fossfreedom ..Sorry for delay .. i started to play with it but have you removed the ability to custom the color ?

**Comment by fossfreedom** [comment]
No no. Everything has now been merged to the master branch. The sassc bits are now there so it should be easier to plugin customizations like maia

**Comment by Ste74** [comment]
@fossfreedom are you sure ? I don't find the `--with-custom` option in the source .. if try to compile with this option `confing` warning me for an unrecognized option ..

**Comment by fossfreedom** [comment]
Ah. No. I didn't get time to add that. It still needs to be done.

**Comment by Ste74** [comment]
No problem .. i rebuild my variation for now with my pkgbuild .. Not know what the option do but i think is better if possible and sorry if already you think this : when the --with-custom run do you think to append the name of the variation color ?

**Comment by fossfreedom** [comment]
I think that's the easiest to understand for everyone. It will make it a good generic way for everyone to work with.

**Comment by NicoHood** [comment]
I will close this issue now, as no problem really exists.
