### ISSUE TITLE
Outdated links in readme

### ISSUE THREAD

**Issue by NHOrus** [NicoHood/arc-theme#121]
It appears that @horst3180 also abandoned Arc Icon Theme, so ti would be advantageous to point to their new upstream, as it appears.

https://github.com/arc-theme/arc-icon-theme

Also, scriptkitties haven't updated their version of ebuild for gentoo for two years, i suggest pointing to https://github.com/fkmclane/overlay

**Comment by NicoHood** [comment]
Please open a PR with the link updates :)
