### ISSUE TITLE
[Solved]]GTK2 full charged  battery icon is  too  big

### ISSUE THREAD

**Issue by FateRover** [NicoHood/arc-theme#122]
install arc-theme from  debian package ,i noticed that the full charged battery icon is much biger than others
https://i.imgur.com/qEP6zWD.png
 i used to think it is a icon issue,but after test all icon,it's a theme issue,can u check it
### Details
```
OS: Debian GNU/Linux testing (buster) x86_64 

Kernel: 4.18.0-1-amd64 
Shell: bash 4.4.23 
Resolution: 1920x1080 
DE: Xfce 
WM: Xfwm4 
WM Theme: axe 
Theme: Arc [GTK2] 
Icons: Adwaita [GTK2] 
Terminal: xterm 
```
here is what used to be in numix theme,same issue,but nowday has been fixed.
https://github.com/numixproject/numix-icon-theme/issues/107#issuecomment-59016997

**Comment by FateRover** [comment]
one more info :it seems  it just happen when the xfce panel height is 24~38,other height ,the icon will scale  the right size 
https://i.imgur.com/ujgNKNy.png

**Comment by shoeper** [comment]
And what is wrong?

With arc-icon-theme there are no issues and also from your screenshots I don't see any issues. To me it looks like the icon form your icon theme uses the full height.

**Comment by FateRover** [comment]
> And what is wrong?
> 
> With arc-icon-theme there are no issues and also from your screenshots I don't see any issues. To me it looks like the icon form your icon theme uses the full height.

obviously bigger than others and  i mean arc-theme,not arc-icon-theme  in debian repo
this is the icon  with arc-theme
https://i.imgur.com/7qZw8OR.png
and  this  is the same icon with  others gtk-theme
https://i.imgur.com/HzvEAew.png
set the xfce4 panel height  34  ，easy  to  reproduce

**Comment by Podesta** [comment]
I don't think it's the theme. Had a similar problem with a couple icons on xfce. Please take a look at this thread. https://forum.xfce.org/viewtopic.php?id=11626

**Comment by shoeper** [comment]
> i mean arc-theme,not arc-icon-theme in debian repo

yes I understood. But arc-icon-theme is an icon theme es adwaita is. At least I cannot reproduce the issue with arc-theme and arc-icon-theme, that is why I think there is no issue with arc-theme.

**Comment by FateRover** [comment]
it seem this issue just occured while xfce panel was 34~38,maybe depends on my screen 1920*1080,slide the panel height to see whether can reproduce it or not .thx

**Comment by Podesta** [comment]
@FateRover Did you even bother at all at going to the link I posted?

**Comment by FateRover** [comment]
> @FateRover Did you even bother at all at going to the link I posted?

 YES i did

**Comment by Podesta** [comment]
So I'm sure you have understood that the problem is not related to either arc theme or arc icons. It is all about the xfce environment (the panel and the applets).

And since you are still having problems, after trying the proposed solutions on that thread, could you further clarify what happened? Maybe post a couple screenshots of the before and after implementing those solutions.

**Comment by FateRover** [comment]
Actually,i have read that link before open this issue long times ago,yes,few monthes  ago.the key is that this is relate with xfce4 4.12 for not fully ported to GTK3 ,some other themes like numix used to have same issue,but finally, numix patch it.
the problem is the icon dosnt scale smooth,seems like missing some size icon and lead a sudden change and bigger than others icon(battery icon become bigger earlier than others icon do),the gif show that ( arc theme + Dual icon) 
https://imgur.com/otAsscD
 the one insist can not reproduced maybe use a fully packed distro while i build my os by mini-install whithout DE but only xorg at first.some other dependencies unlisted may fixed  ,i think(however GTK3-ENGINES-XFCE ANDGTK2-ENGINES DO NOT FIXED ).but not everyone  use fully packed distro

**Comment by FateRover** [comment]
Never waste my words anymore.i will fix it myself.closed it. wasting time.

**Comment by macearl** [comment]
If you do fix it, might i suggest you open a Pull Request here?
