### ISSUE TITLE
Minor glitch on new Nautilus 3.30 pathbar

### ISSUE THREAD

**Issue by daniel88ferreira** [NicoHood/arc-theme#124]
Hi,

- Distribution (with version): Arch Linux
- Desktop environment (with version): gnome-shell 3.30
- Arc version/commit (don't put "latest"): 20180715
- GTK+ 3 version:
  - Murrine engine version: 0.98.2
  - `gnome-themes-standard` version: 3.28
- Installation method (package or source): package: https://www.archlinux.org/packages/community/any/arc-gtk-theme/

![templates_955](https://user-images.githubusercontent.com/23555804/45744936-a129fd80-bbf7-11e8-9e1b-4ed863ff882b.png)

Thanks

**Comment by NicoHood** [comment]
And what is your problem with the picture?

**Comment by somas95** [comment]
I think that Adwaita shows pretty well how this new combo widget should behave and be shown:

Basically Arc lacks a delimiter of the widget's area and has a blue background in the last element of the headcrumb that doesn't belong there
![imatge](https://user-images.githubusercontent.com/8913975/45833901-24d21000-bd06-11e8-8f96-9ffe258a7705.png)

**Comment by dasnoopy** [comment]
...basically, since Nautilus 3.30  has  a new path-bar design: 
https://csorianognome.wordpress.com/2018/07/27/nautilus-3-30/

regards
Andrea

**Comment by somas95** [comment]
I think that Adwaita shows pretty well how this new combo widget should behave and be shown:

Basically Arc lacks a delimiter of the widget's area and has a blue background in the last element of the headcrumb that doesn't belong there
![imatge](https://user-images.githubusercontent.com/8913975/45833901-24d21000-bd06-11e8-8f96-9ffe258a7705.png)

**Comment by NicoHood** [comment]
Please open a PR if you can fix it.

**Comment by daniel88ferreira** [comment]
@somas95 yes, that's the issue I was trying to mention.
@NicoHood I don't know how to fix it, sorry.

**Comment by ruuda** [comment]
As a simpler fix, it would be nice to have a bit of padding around the `/`.

**Comment by spielkind** [comment]
@daniel88ferreira 
https://chipx86.github.io/gtkparasite/
Looks like a nice tool to debug the issue.

To add a 'padding left and right' of the '.dim-label'  / you need to edit the _common.scss file (gtk3 folder). But I guess this is a bit ugly and the whole path-bar needs a redesign.

**Comment by NicoHood** [comment]
I like the fix from @spielkind 
Any objections?

**Comment by jnsh** [comment]
The fix proposed by @spielkind looks good to me.

I think the correct way to implement this, would be adding horizontal margin to `.path-bar button {}`, and it should be done in `_applications.scss`, and somehow limit the change to nautilus only to make sure the change doesn't break the path-bar in e.g. nemo. I can try to figure this out, if no-one has started working on it yet.

For the record, here's how the new path-bar is implemented for Adwaita: https://gitlab.gnome.org/GNOME/nautilus/blob/master/src/resources/css/Adwaita.css#L52

**Comment by jnsh** [comment]
The following rule seems to implement the proposed solution, and also reduces the horizontal padding slightly:
```
.nautilus-window .path-bar>box>button {
  margin: 0 4px;
  padding: 2px;
}
```
Would anyone mind testing this, by adding the above code to your `~/.config/gtk-3.0/gtk.css`, and give some feedback, and report any possible issues. I did test this with nautilus 3.28 and nemo, and both still displayed their path-bars correctly.

If this looks good to everybody, I can open a PR.

It'd still probably be better to redesign the pathbar css based on Adwaita, but I think this works for now.

**Comment by spielkind** [comment]
@jnsh thx, looks good to me :) BTW would love to see your fixes as PR to https://github.com/andreisergiu98/arc-flatabulous-theme as well.

**Comment by jnsh** [comment]
@spielkind , you should open an issue for the arc-flatabulous theme, with references to issues or PRs in this project, and the maintainer can pick up the fixes quite easily.

**Comment by NicoHood** [comment]
A Quick fix was commit in #132 and the redesign was moved to:
https://github.com/NicoHood/arc-theme/issues/133

**Comment by NicoHood** [comment]
@jnsh With the latest release the marked folder is still too large. I am running gnome 3.30.1, maybe that is the problem that will get fixed with 3.30.2?

**Comment by jnsh** [comment]
@NicoHood The gnome release version doesn't matter, only the version of nautilus. With nautilus 3.30.2 everything should be displayed correctly. If you're running up to date Arch linux, you should already have nautilus 3.30.2.

> With the latest release the marked folder is still too large. 

I'm not sure what you mean by that. If you're using nautilus 3.30.2 and there's still something wrong, please open a new issue with more detailed description and screenshots.

**Comment by NicoHood** [comment]
I do have the latest version. I swear I did restart the gnome shell and closed all nautilus windows. It crashed some hours ago and looking at it again it looks nice now. Nevermind...

Thanks for all your great work in this release! Your know how about themeing is really important to us.
