### ISSUE TITLE
[GNOME 3.30] Volume/Brightness sliders are difficult to see 

### ISSUE THREAD

**Issue by spielkind** [NicoHood/arc-theme#125]
### Details

- Distribution (with version): ArchLinux 
- Desktop environment (with version): gnome-shell 3.30.0+25+g179cd0a3c-1
- Arc version/commit (don't put "latest"): arc-solid-gtk-theme-git 20180715.r16.b05cc9d-1
- GTK+ 3 version: 3.24.1
- Installation method (package or source): https://aur.archlinux.org/packages/arc-solid-gtk-theme-git/

Volume/Brightness sliders are difficult to see (dark background)
![screenshot from 2018-09-19 21-08-41](https://user-images.githubusercontent.com/4437264/45776122-39ed6700-bc52-11e8-893c-bc473a9a13b4.png)

**Comment by NicoHood** [comment]
If you can, please provide us with a patch/PR.

**Comment by spielkind** [comment]
Actually I'd love to, but I've never wrote/edited any themes/css. I'll try as soon as I have some spare time.

**Comment by spielkind** [comment]
Ok, if I read this correct: 
https://gitlab.gnome.org/GNOME/gnome-shell/blame/3.30.0/data/theme/gnome-shell-sass/_common.scss
the background color should be `insensitive_bg_color` which is set to:
`@define-color insensitive_bg_color #fbfbfc;` - so it's may be a bug in gnome-shell not in the theme?
