### ISSUE TITLE
 Network-manager-applet has transparent or black look to left and bottom

### ISSUE THREAD

**Issue by erikdubois** [NicoHood/arc-theme#128]
Systembar, network-manager, icon right mouse click, connection information

version of gtk3  3.24.1+2+ged57e564a9-1  (recent update on Arch Linux)
distribution : Arch Linux / ArcoLinux 18.9.5
desktop xfce 4.12
arc-gtk-theme : 20180715-1
gtk-engine-murrine : 0.98.2-3
gnome-themes-extra only available : 3.28.1
Installation method (package or source): pacman -S arc-gtk-theme from community

This is a screen shot how it looks now.
**The right and bottom border was black at first. After reboot it became transparent.**
Hope it helps you to figure out what is going on.

![look](https://user-images.githubusercontent.com/10594806/45968587-ba84dc80-c031-11e8-89a5-73ce54a72616.jpg)

I have hidden the information with black boxes. That is NOT the issue.

**Comment by NicoHood** [comment]
So what is the issue? black or transparent? Can you please make another screenshot?
If a reboot is required, I would not call it a bug in first place, because firefox for example also requires a restart (of the application) in order to work properly. And your applet is part of the Desktop, so a logout/login might be required and normal.

**Comment by erikdubois** [comment]
Both of them have happened. Either it is black or after reboot (I think) it is transparent.
![black](https://user-images.githubusercontent.com/10594806/46030831-8e339380-c0f7-11e8-909c-b1f7a5c6170a.jpg)

**Comment by erikdubois** [comment]
![arcolinux_2018-09-25_21-48-04](https://user-images.githubusercontent.com/10594806/46038969-ca252380-c10c-11e8-99a2-61c20ee0cff2.png)
ArcoLinuxB Openbox - the other was Xfce.
I see it mostly black

**Comment by erikdubois** [comment]
I deleted the pictures again - there was too much interesting information displayed ...

**Comment by erikdubois** [comment]
[img]https://i.imgur.com/LnDvCRv.gif[/img]

**Comment by jnsh** [comment]
If the issue is also reproducible with an up-to-date default Adwaita theme, or whatever is the default for Xfce, then this isn't an issue with the Arc-theme.

If the issue is only reproducible with that single application, you should report it to it's developers.

**Comment by NicoHood** [comment]
Please report he issue upstream then. Or try another Syu update.
