### ISSUE TITLE
Main font color should be darker

### ISSUE THREAD

**Issue by Paviluf** [NicoHood/arc-theme#13]
Hello,

An issue that has been around since the beginning of the Arc theme is the very low contrast. I cause eye-strain for a lot of people !

I will be awesome if you can improve it.

https://github.com/horst3180/arc-theme/issues/406

Thanks !

**Comment by fossfreedom** [comment]
@NicoHood a few pictures will explain this.

So for Arc - the current fonts colours look like this

![ubuntu budgie - new development artful running - oracle vm virtualbox_005](https://user-images.githubusercontent.com/996240/34059219-fd3f6b7a-e1d5-11e7-828e-690a7a8ac7b7.png)

This is the suggested slightly darker version that is proposed in the above link

![ubuntu budgie - new development artful running - oracle vm virtualbox_006](https://user-images.githubusercontent.com/996240/34059231-0c986c52-e1d6-11e7-8f3e-fe3d4f6c54e8.png)

And finally the completely black font colour giving the most contrast

![ubuntu budgie - new development artful running - oracle vm virtualbox_007](https://user-images.githubusercontent.com/996240/34059238-12920e24-e1d6-11e7-8b85-2ef1c2488f93.png)

I couldnt figure out how to get GTK+2 app menus (File - Edit etc)  though to be similarly coloured - the submenus can be coloured though by changing the text-color ang fg-color values here https://github.com/NicoHood/arc-theme/blob/master/common/gtk-2.0/gtkrc

**Comment by NicoHood** [comment]
I like the slightly darker version. It really gives better contrast.

**Comment by Paviluf** [comment]
I think a little more darker than the darker one but less dark than the darkest one will be great.

**Comment by fossfreedom** [comment]
@Paviluf this this PR will resolve - but I do recommend testing this "darkenfonts" branch

https://github.com/NicoHood/arc-theme/pull/15

**Comment by Paviluf** [comment]
Well I can't test for now but the more I look at the screenshot you did, the more I like the darkest one.
Thanks !

**Comment by NicoHood** [comment]
@Paviluf Please make sure to test the next release ;) Thanks for the input.
You might also want to comment on this one: https://github.com/NicoHood/arc-theme/issues/25

**Comment by Paviluf** [comment]
I just tested it from master and it's much better. Thanks !
