### ISSUE TITLE
Missing sliders in Gnome 3.30

### ISSUE THREAD

**Issue by uncles-a-m** [NicoHood/arc-theme#134]
In Manjaro-Linux 17.1.12 with Gnome-Shell 3.30.0+37+g969eecb88-1 sliders are missing (see attached screenshot) in arc-themes-breath  20180715-1, gtk-engine-murrine 0.98.2-3. (Everything installed from package of testing-repo)

**Comment by uncles-a-m** [comment]
Attachment was missing:
https://ibb.co/mBpn9K

**Comment by NicoHood** [comment]
This looks like a manjaro bug. I do not have this on archlinux.

**Comment by jnsh** [comment]
Checkout and build the theme from https://github.com/NicoHood/arc-theme/ without additional patches or tweaks, and report back if the problem persists. Otherwise you should report the issue to the manjaro package maintainers.

**Comment by NicoHood** [comment]
I just did a system upgrade and there is nor bug. Please update your system or consult the manjaro team.
