### ISSUE TITLE
Glitch in gnome-shell 3.30 status-menu sub-menus

### ISSUE THREAD

**Issue by jnsh** [NicoHood/arc-theme#135]
There's a visual glitch at the bottom edge when closing sub-menus on the status menu, seen here:
![screencast_from_09-06-18_12_46_28-0021](https://user-images.githubusercontent.com/39574454/46322476-c7856b00-c5f1-11e8-9ca5-99ab7601d23b.gif)

This results from texture catching that was added in gnome-shell 3.30, and reported upstream [here](https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/73#note_236051). Unfortunately this seems to effect only Arc theme, as I explained [here](https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/73#note_297840):

> Apparently, the reason why this isn't reproducible when using default shell theme, is that Arc [is using border-image for theming the sub-menu background](https://github.com/NicoHood/arc-theme/blob/master/common/gnome-shell/3.18/sass/_common.scss#L625), while the default shell theme [simply sets up background-color and box-shadow](https://gitlab.gnome.org/GNOME/gnome-shell/blob/master/data/theme/gnome-shell-sass/_common.scss#L509). If I remove the border-image from Arc shell theme, the glitch is gone, but also breaks the sub-menu theming.

It seems very unlikely that there would be an upstream fix at this point, so this would have to be fixed in the theme.

I have some ideas of how to fix this, but they may require major rework for the gnome-shell theme. I'm working on this next, but wanted to open this issue for a placeholder, since I'd like the fix to be included in the next release. @NicoHood please take note of this. I'll report back if fixing this seems to take unreasonable amount of time for holding the release.

**Comment by NicoHood** [comment]
On ArchLinux I do not see this issue (with the latest stable release). But I also have snome-shell 3.30, so I am not sure why you see this issue.

**Comment by jnsh** [comment]
@NicoHood, As I mentioned in the upstream PR comments, this Issue seems to only effect the Arc gnome-shell theme. I've gathered from your other posts that you are not using the Arc shell theme but sticking with the default look, in which case you wouldn't experience this issue. If my assumption is correct, would you mind enabling either of the Arc shell themes from Tweak tool, and trying to reproduce the issue again?

**Comment by jnsh** [comment]
I think I figured out an almost faultless workaround for this issue. It's still kind of a hack, but the only perfect solution for this issue that I can think of, is to stop using .svg assets for drawing the menus altogether. The workaround does just that, but only for the sub-menu-items, and it's not super pretty. I'll open a PR ASAP.

@NicoHood It would be great if you were able to test the fix, and other future updates for the shell themes. You only need to enable "User themes" extension from the `extra/gnome-shell-extensions` package, and switch the shell theme to Arc in gnome-tweaks.

**Comment by NicoHood** [comment]
I currently aint got time to test anything, I am sorry. The more I am happy that you are helping us all out here :)

**Comment by jnsh** [comment]
@NicoHood Even simply using the theme and reporting any oddities would be helpful, but I can certainly understand if you don't have time for doing testing.

I added a PR with the workaround to this issue.
