### ISSUE TITLE
white separator line between Thunar pathbar and sidebar

### ISSUE THREAD

**Issue by macearl** [NicoHood/arc-theme#137]
With the latest Thunar update (1.8.2-1) there is a white separator between the top pathbar and the sidebar

before:
![before](https://user-images.githubusercontent.com/1804541/46412351-99517980-c71e-11e8-8006-a9596daf7c6b.png)

after:
![after](https://user-images.githubusercontent.com/1804541/46412358-9ce50080-c71e-11e8-9b99-1610566ca906.png)

Distribution: Arch Linux
Desktop environment: i3
Arc version: 20180715-1
GTK3 version: 3.24.1+2+ged57e564a9-1
Installation method: Arch package

I'm unable to test the latest git version, see my other opened issue

**Comment by NicoHood** [comment]
I think this was recently fixed. We are preparing for a new release soon. Please be patient.

**Comment by macearl** [comment]
You are right, i just build arc by hand with the `--disable-gnome-shell` flag which got me past the build error and the white line is gone, this can probably be closed then
