### ISSUE TITLE
Nautilus adressBar have white backgound on larger screen

### ISSUE THREAD

**Issue by pieplu** [NicoHood/arc-theme#139]
### Details

- Distribution (with version): Arch Linux from today (04 oct 2018)
- Desktop environment (with version): Gnome 3.30
- Arc version/commit (don't put "latest"): 20180715
- GTK+ 3 version:
  - Murrine engine version: 0.98.2
  - `gnome-themes-standard` version: (gnome-themes-extra? : 3.28)
- Installation method (package or source): AUR

Since nautilus 3.30.1, on larger screen (when it will be center), adresse bar take a white bacground:
![image](https://user-images.githubusercontent.com/3260285/46498025-3fb68100-c7ea-11e8-8bea-934560eae3ae.png)

On smaller screen, evrything looks normal:

![image](https://user-images.githubusercontent.com/3260285/46498410-60cba180-c7eb-11e8-87e0-37597d40c256.png)

**Comment by BooBerry** [comment]
I'm seeing this too with 3.30.1 so I can confirm.

**Comment by jnsh** [comment]
Can you try pulling the latest revision from this git repo, or arc-gtk-theme-git from AUR? I can't reproduce with it.

**Comment by BooBerry** [comment]
Already using it, same result.

**Comment by aldomann** [comment]
Note that it affects the three variants, not only the `Darker` one, as seen in the picture below (standard, darker, and dark variants respectively).

![arc-bug](https://user-images.githubusercontent.com/729732/46569537-e455d180-c956-11e8-80e8-926e7bcee8ab.png)

Even in the `Dark` variant, a box widget is being drawn around the addressBar (compare with the picture of the standard behaviour posted by @pieplu).

**Comment by jnsh** [comment]
@aldomann, This issue was only about the white background.

I suppose it's best to address this issue by properly redesigning the path-bar in #133 

In the meanwhile you can remove the white background, and border by adding one of the following snipplets to your user's `~/.config/gtk-3.0/gtk.css`

For Arc, and Arc-Dark:
```
.nautilus-window .path-bar-box {
  background-color: transparent;
  border-color: transparent;
}
```
For Arc-Darker:
```
.nautilus-window .path-bar-box {
  background-color: transparent;
  border-color: transparent;
  color: #D3DAE3;
}
```

**Comment by aldomann** [comment]
@jnsh that does the trick until the path-bar is redesigned. Thanks :+1:
