### ISSUE TITLE
Feature Request: Window decoration options

### ISSUE THREAD

**Issue by LordZane** [NicoHood/arc-theme#153]
Being able to have Windows 10 / macOS style window decorations, on the left or right side would be a good option to add. I could try to take a look at recreating it using css in a codepen if that would help. For macOS specifically, many themes have adapted this theme before so it shouldn't be hard to find some examples.

**Comment by jnsh** [comment]
The window button placement is already configurable with most window managers/desktop shells that are supported by Arc. You just need to configure it from your WM/desktop settings, and it has nothing to do with the theme.

I checked that this should be the case at least with GNOME Shell, Cinnamon, XFCE and Openbox. I couldn't confirm whether this is possible in Unity or Metacity, although even with those two, I doubt that anything could be done from the theme's side.

**Comment by LordZane** [comment]
Didn't know window decoration position was not up to the theme implementing, thanks for letting me know. That said, did you close this because you didn't want to add Windows 10 and macOS style decorations (style wise)? Just want to make sure you understood my question, no problem if you don't want to. Thanks for maintaining my favorite theme!

**Comment by jnsh** [comment]
Frankly, I was a bit unsure what you meant, but to me it made most sense that this was about the position of the window decoration buttons. I'm assuming the issue was closed by that basis.

Could you clarify what you are suggesting exactly, since just saying "Windows 10 / macOS style window decorations" is rather ambiguous.

**Comment by LordZane** [comment]
https://imgur.com/a/mEB1dTj
