### ISSUE TITLE
--with-gtk3 broken for 3.28/3.30

### ISSUE THREAD

**Issue by fossfreedom** [NicoHood/arc-theme#154]
Current master.

Reminder to look at this further - if passing the above to values autogen.sh (configure) fails with a GTK3 too new error message.

**Comment by jnsh** [comment]
What exactly is the issue?
There's no GTK3 version 3.28 or 3.30. GTK 3.24 is the latest version.

**Comment by fossfreedom** [comment]
I am going quite mad. Yeah you are right. Non issue.
