### ISSUE TITLE
Install to user local ~/.themes?

### ISSUE THREAD

**Issue by kmansoft** [NicoHood/arc-theme#162]
First thanks for a great theme, looking to replace the "arc" in my distribution with some tweaks (like darker text color).

So these are questions not a bug report.

- Distribution (with version): Fedora 29
- Desktop environment (with version): XFCE 4.13
- Arc version/commit (don't put "latest"): latest :) 416696720bd30702a16f95f042f0f19f261d73cd
- GTK+ 3 version: 3.24.1
  - Murrine engine version:0.98.2
  - `gnome-themes-extras` version: not installed
- Installation method (package or source): source

-----

Is there support for installing into the user local `~/.themes` directory?

I tried this:

```
./autogen.sh --prefix=/home/username/.themes
...
make
make install
```

but it looks wrong, e.g.:

```
/usr/bin/install -c -m 644 $files "/home/user/.themes/share/themes/Arc-Darker"
```

Alternatively, I could symlink from `~/.themes` into actual theme directories - except it seems that the build process does not create a directory structure anywhere under the build directory that would matches the standard theme directory structure.

I mean there is no

```
Arc-Darker
  gtk-2.0
  gtk-3.0
  metacity-1
  xfwm4
```

anywhere in the source / build directory after `make` that I could just `ln -s` from `~/.themes` is there?

**Comment by jnsh** [comment]
> First thanks for a great theme

All thanks should go to @horst3180 who designed the theme originally, but has been MIA for quite some time.

Try `./autogen.sh --prefix=/home/username/.local`. That will install it to `~/.local/share/themes`, which should work just as well as `~/.themes/`

**Comment by kmansoft** [comment]
> Try ./autogen.sh --prefix=/home/username/.local. That will install it to ~/.local/share/themes, which should work just as well as ~/.themes/

Yeah thanks.

What worked for me too was `--prefix=$PWD/temp` and then `ln -s` from `~/.themes` to that `temp` directory :)
