### ISSUE TITLE
new xfce4-screensaver doesnt style properly lock dialog with standart Arc theme

### ISSUE THREAD

**Issue by avbdr** [NicoHood/arc-theme#168]
XFCE team came with their own fork of mate-screensaver (https://git.xfce.org/apps/xfce4-screensaver/) which should share styles with LightDM Greeter. You can see brief description at https://bluesabre.org/2018/10/15/xfce-screensaver-0-1-0-released/#gallery-2829-1-slideshow

 
Currently locker screen works properly with Adwaita and Greybird theme, but have several glitches while using Arc such as:
1. Locker window looks as it is not drawn in full.  
2. On a password entry dialog is not showing masked input chars in the password GtkEntry.      
On the attached screenshot I have already entered 'test' as a password and im expecting to see '****' in the password GtkEntry box. 

Im using latest debian testing.
arc-theme 20181022-1
XFCE 4.12 + part 4.13
GTK+ 3.24.1-2
gtk2-engines-murrine 0.98.2-2
gnome-themes-extra 3.28-1

Everything is installed from the debian packages.
Thank you.
![lock](https://user-images.githubusercontent.com/3286514/48775395-4bc7a680-eca3-11e8-9e31-dcc2b316e883.png)

With Adwaita
![lock-adwaita](https://user-images.githubusercontent.com/3286514/48775554-c264a400-eca3-11e8-8b67-99433952ddc6.png)

**Comment by CaffeinePizza** [comment]
I'm also suffering this issue. If there is any way I can assist in resolving this bug, please let me know.

**Comment by avbdr** [comment]
its appeared to be a bug in the screensaver code itself. 
future release might include a fix for it
