### ISSUE TITLE
XFCE4 (Debian): Menu highlight color not working

### ISSUE THREAD

**Issue by m3hm00d** [NicoHood/arc-theme#169]
### Details

- Distribution (with version): Debian Stretch
- Desktop environment (with version): XFCE 4.12
- Arc version/commit (don't put "latest"): version: 20161119-1(package) / commit: e97206c(source)
- Installation method (package or source): both

**Installation:**
I installed Debian server and then installed "task-xfce-desktop". Then installed arc-theme from debian repo. Everything looks and works fine except menu highlight colors.

I tried arch-theme from debian stretch repo and also built arc-theme following the instructions on README. This problem happens with both versions.

**Arc and Arc-Darker:**
The menu highlight color is probably white. So the entire menu item gets washed by white. Text gets hidden. No blue highlight:
[Arc-Darker screenshot (arc-theme built from source)](https://i.imgur.com/JHFt0mf.png)

**Arc-Dark:**
The menu item under the cursor gets a little glow on the text. Still no blue highlight on the menu item.
[Arc-Dark screenshot (arc-theme installed using apt)](https://i.imgur.com/cxd9fLM.png)

Other themes, such as Adwaita' and 'Adwaita-Dark' have no problem with menu highlighting.

**Comment by NicoHood** [comment]
Your version is way too old. Please install the latest version of the theme.

**Comment by m3hm00d** [comment]
As mentioned in the bug report, I tried debian package first using apt. But this issue occured. Then I cloned your latest github repo and built from source. Same issue.

Regards.

**Comment by xhc1** [comment]
I am using Debian stable (Stretch) Xfce
(minimal-net installer iso)

I installed arc-theme version: 20161119-1 from official stable repo:
**I have no issues with menu highlight color at all**

**Comment by NicoHood** [comment]
Please comment if the issue occurs again
