### ISSUE TITLE
Icon used in the snapshot

### ISSUE THREAD

**Issue by arshadkazmi42** [NicoHood/arc-theme#172]
Its not exactly an issue, its a question.

I want to know the icon pack name, which is being used in this snapshot

https://camo.githubusercontent.com/4c0001cbfe222446c4b3af91027b716daec7d3d7/687474703a2f2f692e696d6775722e636f6d2f5068354f624f612e706e67

Which I found from README.md

**Comment by drakkar1969** [comment]
White Pixel icons, scroll to the very bottom of the README for a link

**Comment by arshadkazmi42** [comment]
Thanks for pointing to that. I completely missed it.

**Comment by arshadkazmi42** [comment]
Those icons and just .ico files ziped. Is there a way to install those icons? @drakkar1969

**Comment by drakkar1969** [comment]
Sorry, I'm afraid I can't help you there
