### ISSUE TITLE
Dynamic transparency for GNOME panel (top bar)

### ISSUE THREAD

**Issue by drakkar1969** [NicoHood/arc-theme#173]
Would there be any interest in implementing dynamic transparency for the GNOME panel (like the Adwaita theme does in newer versions of gnome shell)?

Screenshots (with modded Arc-Dark shell theme):

![normal](https://user-images.githubusercontent.com/18715287/49686287-9db95a80-faf2-11e8-8a44-3b69e3152636.png)
![max](https://user-images.githubusercontent.com/18715287/49686288-a1e57800-faf2-11e8-9b56-26000431ac80.png)

It would only require a couple of changes in the gnome shell css:

Need to change this:
```
#panel {
  font-weight: bold;
  height: 2.1em;
  min-height: 27px;
  background-gradient-direction: none;
  background-color: transparent;
  border-bottom-width: 0;
  border-image: url("common-assets/panel/panel.svg") 1 1 1 1; }
```
to:
```
#panel {
  font-weight: bold;
  height: 2.1em;
  min-height: 27px;
  background-gradient-direction: none;
  background-color: transparent;
  border-bottom-width: 0;
  border-image: none; }
#panel.solid {
  border-image: url("common-assets/panel/panel.svg") 1 1 1 1; }
```
And this:
```
#panel:overview {
  border-image: url("common-assets/panel/panel-overview.svg") 1 1 1 1; }
```
to:
```
#panel:overview {
  border-image: none; }
```
I can make a PR if helpful

### Details

- Distribution (with version): Arch Linux
- Desktop environment (with version): GNOME 3.30
- Arc version/commit (don't put "latest"): 20181022
- GTK+ 3 version: 3.24.1
  - Murrine engine version: 0.98.2
  - `gnome-themes-extras` version: n/a
- Installation method (package or source): Arch AUR package

**Comment by drakkar1969** [comment]
it appears to be permanent, i.e. there is no setting to turn on and off

**Comment by NicoHood** [comment]
I like the idea, and I think there was some post about that before!?

**Comment by drakkar1969** [comment]
Ok, opened a pull request: #175

**Comment by feren** [comment]
Too bad that it looks like GNOME is now REMOVING panel translucency for non-maximised windows by the sounds of it...
https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/376

**Comment by NicoHood** [comment]
I've seen this too. Do we need to change our theme or can we leave it as is?

**Comment by fossfreedom** [comment]
@NicoHood we should revert - https://github.com/NicoHood/arc-theme/pull/193
