### ISSUE TITLE
Make Arc Darker text the same color as Arc

### ISSUE THREAD

**Issue by v44r** [NicoHood/arc-theme#182]
The Arc (light) default font color is a bit darker than the default font color in Arc-Darker, and that extra contrast helps a lot in readability. It would be nice to have the darker font also in Arc-Darker.

**Comment by v44r** [comment]
BTW, since I realized I was not clear on the previous message: I meant the gtk-2.0 part of Arc-Darker. The change is simply replacing #5c616c with #3b3e45 in common/gtk-2.0/darker/gtkrc, as was done in common/gtk-2.0/light/gtkrc and the gtk-3.0 part of the theme.

**Comment by fossfreedom** [comment]
Can you add screenshots with the before and after for the change?

Better still - can you do a pull-request please which includes the
screenshots?
