### ISSUE TITLE
Create a new stable release

### ISSUE THREAD

**Issue by fossfreedom** [NicoHood/arc-theme#184]
@NicoHood please can you create a new stable release as soon as reasonably possible.

Debian soft-freeze is in a couple of weeks and I need to upload the latest before the package upload door shuts.

TIA

**Comment by NicoHood** [comment]
Which of the open PRs should we merge until then?
https://github.com/NicoHood/arc-theme/milestone/4

When is the deadline?

**Comment by fossfreedom** [comment]
today.  None of the open PR's are urgent enough to stop this release.

**Comment by NicoHood** [comment]
Done. We have to cleanup the milestone etc. Sorry for the late reply.

**Comment by fossfreedom** [comment]
Much appreciated :)

On Wed, 13 Feb 2019, 18:10 Nico <notifications@github.com<mailto:notifications@github.com> wrote:

Done. We have to cleanup the milestone etc. Sorry for the late reply.
