### ISSUE TITLE
Please do not hardcode fonts

### ISSUE THREAD

**Issue by ManuelSchneid3r** [NicoHood/arc-theme#185]
Why is [the font hardcoded](https://github.com/NicoHood/arc-theme/blob/master/common/gnome-shell/3.18/sass/_common.scss#L29)? Aint there a way to inherit the system font?

### Details

- Archlinux
- Cinnamon 4.0.9
- [arc-gtk-theme-git 20180715.r3.b12b2e7-1](https://aur.archlinux.org/packages/arc-gtk-theme-git/)
- gnome-themes-extra 3.28-1
- from arch repo

**Comment by fossfreedom** [comment]
Its just the way the theme original designer decided the best fonts for the theme should be - so starting with the preferred font and if not available, looking at the next one and so on.

Seems an entirely reasonable approach  - the theme maker obviously wants you to use his/her preferred font to showcase their theme.

**Comment by fossfreedom** [comment]
just add your font family name to the front of the other font names then it will be used when you compile and install.


On Wed, 30 Jan 2019 at 14:26, Manuel Schneider <notifications@github.com<mailto:notifications@github.com>> wrote:
Sorry for not beeing precise. Im fine with the author beeing able to override the font. My problem is that I cannot comment the line to use my system font.
