### ISSUE TITLE
dash-to-dock after 20190213-update inconsistent

### ISSUE THREAD

**Issue by Tids** [NicoHood/arc-theme#195]
on gnome 3.30 (Archlinux), after the latest arc update, the top panel will go to full transparency if there is no window "docked" to it. This makes the desktop feel really ugly in case you use dash-to-panel as you can see here
![bildschirmfoto von 2019-02-18 08-31-31](https://user-images.githubusercontent.com/18744080/52935211-14779d00-3359-11e9-8c48-2fc2dc3ea984.png)

It would be nice if there would be a change to make dash-to-dock look nice, or to not go transparent in case of dash-to-dock

**Comment by Tids** [comment]
On the desktop now
![bildschirmfoto-20190218235619-3840x2160](https://user-images.githubusercontent.com/18744080/52980102-d91cb300-33d8-11e9-8007-d394625022d6.png)
So seems to be that this is no bug. + Itea REALLY hard to read on bright wallpapers.

**Comment by Tids** [comment]
Ohh looks like this will bring back the old behavior: https://github.com/NicoHood/arc-theme/pull/193

**Comment by daviian** [comment]
This is not restricted to dash-to-dock alone. Can be also observed with dock-to-panel.

![dock-to-panel](https://user-images.githubusercontent.com/5477981/53012596-b2e02d00-3443-11e9-94cb-7d458268b55c.png)

**Comment by NicoHood** [comment]
@Tids Did you confirm the linked PR fixes your problem? @daviian could you please also try? I am happy to merge it then.

**Comment by daviian** [comment]
@NicoHood I can confirm that the PR fixes the problem.
