### ISSUE TITLE
Cinnamon fixes for window-list-item-box (icon spacing, font weight)

### ISSUE THREAD

**Issue by phpony** [NicoHood/arc-theme#201]
This theme looks ugly when you have windows list with labels. There's no spacing between window icon and window title, and font is all bold.

This little snippet will fix the issue:
```
.window-list-item-box StLabel {
  padding-left: 5px;
}

.window-list-item-box {
  font-weight: normal;
  ...
}
```

Just compare this screenshots:

- before:
![Before](https://i.imgur.com/Mvb8e6v.png)

- after:
![After](https://i.imgur.com/kSqNzmB.png)

Can create a pull request if you're interested.

**Comment by phpony** [comment]
This is a repost from there cause that repo seems dead: https://github.com/horst3180/arc-theme/issues/900

Already implemented in: https://github.com/vinceliuice/matcha/issues/44

**Comment by fossfreedom** [comment]
PR would be most welcome

**Comment by smurphos** [comment]
I don't think the padding/spacing between icon and label is a problem in current master in this repo. T

The bold font weight is still in place from Horst's original and emulated in the grouped-window-list applet theming as-well. I'd personally also have it at a smaller default font size as-well as non bold, but maybe keep the focused app bolded.

**Comment by NicoHood** [comment]
Could you please open a pr?

**Comment by smurphos** [comment]
Will do..

**Comment by NicoHood** [comment]
Any progress?

**Comment by smurphos** [comment]
Sorry - not yet - I'll find sometime tomorrow and get it done.
