### ISSUE TITLE
Strange upper page color Arc Dark Theme on XFCE Debian

### ISSUE THREAD

**Issue by LodocArt** [NicoHood/arc-theme#203]
- Distribution (with version):
   - Debian 9.7
- Desktop environment (with version):
   - Xfce 4.12
- Arc version/commit (don't put "latest"):
   - I'm installing for the packages, so with the command apt-get install arc-theme (20161119-1 from the terminal log)
- GTK+ 3 version:
   - 3.22.11-1
- Installation method (package or source):
   - From the package

I'm having a strange color problem. For all dark modes in my xfce, it has this strange color gradient, as shown in the first screenshot 
![2](https://user-images.githubusercontent.com/43345969/53684456-db064080-3d0d-11e9-8d09-378cf78ccbc8.PNG)

The arc light theme works normally, but the arc darker theme only has some elements in dark ( the second screenshot )
![3](https://user-images.githubusercontent.com/43345969/53684465-ff621d00-3d0d-11e9-8c75-23170611db70.PNG)

Thank you for your help ! :D

**Comment by fossfreedom** [comment]
Please do try the latest version in the repo - there has been lots of changes since 2016 so we need to check if this has been resolved.

**Comment by LodocArt** [comment]
I'm trying to build it from the repository, but I have lots of errors, 

** (inkscape:12925): CRITICAL **: dbus_g_connection_register_g_object: assertion 'connection != NULL' failed
/usr/bin/inkscape --export-id-only --export-png="dark/assets/combo-entry-button-insensitive.png" --export-id="combo-entry-button-insensitive" --export-dpi=96 "dark/assets.svg" >/dev/null
Failed to get connection
** (inkscape:12927): CRITICAL **: dbus_g_proxy_new_for_name: assertion 'connection != NULL' failed

** (inkscape:12927): CRITICAL **: dbus_g_proxy_call: assertion 'DBUS_IS_G_PROXY (proxy)' failed

** (inkscape:12927): CRITICAL **: dbus_g_connection_register_g_object: assertion 'connection != NULL' failed
/usr/bin/inkscape --export-id-only --export-png="dark/assets/combo-entry-button-active.png" --export-id="combo-entry-button-active" --export-dpi=96 "dark/assets.svg" >/dev/null
Failed to get connection
** (inkscape:12930): CRITICAL **: dbus_g_proxy_new_for_name: assertion 'connection != NULL' failed

** (inkscape:12930): CRITICAL **: dbus_g_proxy_call: assertion 'DBUS_IS_G_PROXY (proxy)' failed

** (inkscape:12930): CRITICAL **: dbus_g_connection_register_g_object: assertion 'connection != NULL' failed
/usr/bin/inkscape --export-id-only --export-png="dark/assets/combo-entry-button-rtl.png" --export-id="combo-entry-button-rtl" --export-dpi=96 "dark/assets.svg" >/dev/null
Failed to get connection
** (inkscape:12932): CRITICAL **: dbus_g_proxy_new_for_name: assertion 'connection != NULL' failed

** (inkscape:12932): CRITICAL **: dbus_g_proxy_call: assertion 'DBUS_IS_G_PROXY (proxy)' failed

** (inkscape:12932): CRITICAL **: dbus_g_connection_register_g_object: assertion 'connection != NULL' failed
/usr/bin/inkscape --export-id-only --export-png="dark/assets/combo-entry-button-insensitive-rtl.png" --export-id="combo-entry-button-insensitive-rtl" --export-dpi=96 "dark/assets.svg" >/dev/null
Failed to get connection
** (inkscape:12934): CRITICAL **: dbus_g_proxy_new_for_name: assertion 'connection != NULL' failed

** (inkscape:12934): CRITICAL **: dbus_g_proxy_call: assertion 'DBUS_IS_G_PROXY (proxy)' failed

** (inkscape:12934): CRITICAL **: dbus_g_connection_register_g_object: assertion 'connection != NULL' failed
^CMakefile:729 : la recette pour la cible « dark/assets/combo-entry-button-insensitive-rtl.png » a échouée
make[2]: *** [dark/assets/combo-entry-button-insensitive-rtl.png] Interrompre
Makefile:436 : la recette pour la cible « install-recursive » a échouée
make[1]: *** [install-recursive] Interrompre
Makefile:361 : la recette pour la cible « install-recursive » a échouée
make: *** [install-recursive] Interrompre

I've installed libgtx-3-dev, gtk2-engines-murrine, sassc, gnome-shell and inkscape, but these errors look like an inkscape problem :c

**Comment by ericyan** [comment]
This is a known quirk of XFCE. To fix it, go to `Settings -> Window Manager -> Style`, set the WM theme to Arc Dark as well.

**Comment by qwertychouskie** [comment]
It's not a quirk, it's an intentional visual style.  It just doesn't look good with flat themes. :)
