### ISSUE TITLE
Update for Gnome 3.32

### ISSUE THREAD

**Issue by kaipee** [NicoHood/arc-theme#209]
- Distribution (with version): **Arch Linux**
  - Base distribution (if have, with version):
- Desktop environment (with version): **Gnome 3.32**
- Arc version/commit (don't put "latest"): **20190213.r11.7994fd3-1**
- GTK+ 3 version:
  - Murrine engine version:
  - `gnome-themes-extras` version:
- Installation method (package or source): **AUR : arc-gtk-theme-git**

Package will not build when intsalled from AUR : arc-gtk-theme-git.

```
Building for GTK3 3.20
checking for gnome-shell... yes
configure: error: Invalid gnome-shell version: 3.32
==> ERROR: A failure occurred in build().
    Aborting...
Error making: arc-gtk-theme-git
```

**Comment by NicoHood** [comment]
@fossfreedom should I tag a new release? I also have these icon problems, it uses the gnome default on some icons rather than the arc icon theme. Do we also need to fix something on the icon theme side?

**Comment by fossfreedom** [comment]
GNOME 3.32 changed quite a few icon names - look in the associated /usr/share/applications/....desktop files for the Icon=

All icon themes will need their symlinks updated to ensure symlink icon names reflect the new icon name.

Yes - I would tag a new release given 3.32 is now out in the wild.

**Comment by LP0101** [comment]
Just pitching in here, the top bar is broken if using the last release on GNOME 3.32, however it works if building from source.

**Comment by NicoHood** [comment]
I will tag a new release, then we can update to the new gnome version and fix other bugs afterwards.
