### ISSUE TITLE
Gnome 3.32: calendar text color in panel

### ISSUE THREAD

**Issue by drakkar1969** [NicoHood/arc-theme#212]
With Gnome shell 3.32 update, date/time text color in panel is arc blue:

![normal](https://user-images.githubusercontent.com/18715287/54476090-74971d00-47f9-11e9-96dc-0552f15a171d.png)
![open](https://user-images.githubusercontent.com/18715287/54476093-782aa400-47f9-11e9-9fa4-db20b119d8a3.png)

### Details

- Distribution (with version):
  - Base distribution (if have, with version): Arch Linux
- Desktop environment (with version): Gnome 3.32
- Arc version/commit (don't put "latest"): 20190213
- GTK+ 3 version:
  - Murrine engine version: 0.98.2
  - `gnome-themes-extras` version: 3.28-1
- Installation method (package or source): Arch package `arc-gtk-theme`

**Comment by drakkar1969** [comment]
Just realized this is fixed by #210 - although that PR also reverts the shell font size to 9pt, which would be a pity

**Comment by NicoHood** [comment]
Is the font size a problem? @fossfreedom should we revert that change?

**Comment by drakkar1969** [comment]
Font size has been fixed with commit https://github.com/NicoHood/arc-theme/commit/5b18f6034ab94e7fa557d89bcd7924383e033441, so I think this issue can be safely closed

**Comment by NicoHood** [comment]
Thanks!

**Comment by D4v2z** [comment]
Hello, I have the same issue, Fedora 30 GNOME.
