### ISSUE TITLE
Problems with dash-to-dock extension and Arc theme on GNOME 3.32.0

### ISSUE THREAD

**Issue by FreddieChopin** [NicoHood/arc-theme#220]
### Details

- Distribution (with version):
`Linux 5.0.4-arch1-1-ARCH #1 SMP PREEMPT Sat Mar 23 21:00:33 UTC 2019 x86_64 GNU/Linux`
- Desktop environment (with version):
`GNOME 3.32.0`
- Arc version/commit (don't put "latest"):
`arc-gtk-theme-git 20190330.r0.cadf8d2-1`
- GTK+ 3 version:
`gtk3 1:3.24.7+25+g17665f06e3-1`
- Murrine engine version:
none
- `gnome-themes-extras` version:
`gnome-themes-extra 3.28-1`
- Installation method (package or source):
ArchLinux AUR, git package

After GNOME 3.32 upgrade, the theme does not cooperate well with dash-to-dock extension. Here's the dock with default theme:
![Screenshot from 2019-04-04 10-48-23](https://user-images.githubusercontent.com/1139038/55543018-7f422500-56c8-11e9-8e0e-611843a03868.png)
And here it is with Arc theme:
![Screenshot from 2019-04-04 10-49-03](https://user-images.githubusercontent.com/1139038/55543029-879a6000-56c8-11e9-91fb-6fdba7639a46.png)

As you see with Arc the icons have strange spacing between them, which is somehow not counted when calculating the size of the dock, thus resulting in some icons appearing only partially or being completely out of visible area. It generally gets worse when you open a lot of applications and then close some of them - the spacing between the icons gets even bigger in that case. There is also some ugly spacing below the icons.

Please let me know whether this is an issue fixable in Arc theme or whether it has to be fixed in dash-to-dock extension. This is probably related to #217

**Comment by drakkar1969** [comment]
Also seeing issues with dash to dock with the latest gnome shell update (`3.32.0+46+gfea019277-1`) on Arch. Evidently the changes to dash margins/padding in commit https://github.com/NicoHood/arc-theme/commit/4802bc1fb9270b4e830ccf8361703f4ff698cff4 are messing things up - and are not worth the hassle just to have the running dost visible on hover.
Best solution is to revert the commit I think.

**Comment by FreddieChopin** [comment]
Tested the fix/revert and now the original problem is gone - thanks!
