### ISSUE TITLE
Chrome/Chromium download bar wrong color and unreadable text

### ISSUE THREAD

**Issue by kronikpillow** [NicoHood/arc-theme#222]
Distribution: Archlinux
Desktop environment: Openbox 3.6.1-4
Arc version: community/arc-gtk-theme  20190330-1
Arc variant: Arc-Dark
GTK+ 3 version: 1:3.24.7+25+g17665f06e3-1
Murrine engine version: 0.98.2-3
gnome-themes-extras version: 3.28-1
Installation method: archlinux package
in all Dark variants of Arc-Nico themes the download bar at the bottom of chrome/chromium is white with white text, unreadable, couldn't find a fix anywhere, would really like a fix for it ...
althou in the Darker variants it displays properly

**Comment by NicoHood** [comment]
Could you please post a screenshot?

**Comment by tista500** [comment]
That's an Chrome/ium (ver. 73.0 or newer) issue and theme-independent. This isn't fixed in ver. 75.0 yet, so original reporter should file a issue to upstream instead.

https://gitlab.com/tista500/plata-theme/issues/34
