### ISSUE TITLE
atom editor - cannot read menus with arc-darker theme

### ISSUE THREAD

**Issue by mikewalker** [NicoHood/arc-theme#227]
When using the arc-darker application theme the top menu in atom is not really readable the menu text and the background are almost the same colour. The arc-dark theme does not have the same issue, but do prefer the arc-darker theme which is actually less dark.

I did find a solution that does work since atom is the only application with this issue. What I did was to change the exec line in the atom.desktop file so that the arc-darker theme is used for atom. This  works as a temporary fix but I'd rather not need to be editing desktop files in order to read menus in the app.

Exec=env GTK_THEME=Arc-Dark /usr/bin/atom %F

I am currently using Atom 1.36, Gnome 3.32 on Fedora 30. The issue is also reproducible on Arch linux so this may be a Gnome 3.32+ issue.

**Comment by NicoHood** [comment]
It seems to be gone on my system. But I had this issue also since weeks on ArchLinux.

**Comment by mikewalker** [comment]
I just checked the arch system again and the issue is indeed gone on the arch system. Maybe a slight 

Both systems are both using 20190330 version so maybe a difference in a supporting library? Actually Fedora is 4 commits ahead but I don't think that's it since the problem was there before updating to HEAD.

**Comment by NicoHood** [comment]
I guess it could be the gnome version or atom itself?

**Comment by smurphos** [comment]
Atom is electron based I believe? This sounds like an old electron bug that was patched a while back - https://github.com/electron/electron/pull/15878

**Comment by NicoHood** [comment]
Thanks a lot for this note!

**Comment by mikewalker** [comment]
> Atom is electron based I believe? This sounds like an old electron bug that was patched a while back - [electron/electron#15878](https://github.com/electron/electron/pull/15878)

Thanks for this, it certainly looks like what I've been running into.
