### ISSUE TITLE
transparent tray

### ISSUE THREAD

**Issue by luoc0815** [NicoHood/arc-theme#230]
_(previously posted [here](https://github.com/horst3180/arc-theme/issues/907))_

On Ubuntu 19.04 the tray turns fully transparent once the arc / arc-dark shell theme was selected. I installed the theme from the default Ubuntu repositories.

When building the theme on my own `autogen.sh` raises the followoing error
`configure: error: Invalid GNOME version: 3.24`
respectively 
`configure: error: Invalid GNOME version: 3.32`
if I pass `--with-gnome=3.32` flag.

![Bildschirmfoto vom 2019-04-22 20-28-34](https://user-images.githubusercontent.com/19192307/56517577-87f68000-653d-11e9-874d-a02be522e7a6.jpg)

**Comment by fossfreedom** [comment]
The flag is `--with-gnome-shell=3.32`

Note - on Ubuntu you can install my PPA to get the latest theme updates - PPA details in the README.

**Comment by luoc0815** [comment]
Okay, using the ppa provided by you solves the problem for me. Thanks for that quick response ;)

**Comment by strom18** [comment]
I didn"t see PPA configuration on this project readme.
Where i can find this PPA ?
