### ISSUE TITLE
Keyboard flags icon not visible

### ISSUE THREAD

**Issue by medmedin2014** [NicoHood/arc-theme#233]
Flags icons are all not visible in keyboard indicator
![Public_008](https://user-images.githubusercontent.com/7027319/56869975-31d38200-6a00-11e9-8213-7745b960464d.png)

**Comment by NicoHood** [comment]
What desktop environment is this? Can you please give more information about the arc version and OS version? Does it also happen with other themes?

**Comment by medmedin2014** [comment]
I use Ubuntu Mate 18.04.2 - 64bits, and arc-theme package version 20190330+201904240732~ubuntu18.04.1 installed from ppa:fossfreedom/arc-gtk-theme-daily
This problem happens with other theme when I use keyboard layout like arabic.

**Comment by NicoHood** [comment]
Then it is no problem of the theme, but a problem with the mate desktop.
