### ISSUE TITLE
Selected item in Caja dual panel are white

### ISSUE THREAD

**Issue by medmedin2014** [NicoHood/arc-theme#234]
When using dual panel in Caja file manager and selecting one item in the first pane then selecting second item in the second pane, the first selected item is white and not visible.
![Screenshot at 2019-04-28 21-57-03](https://user-images.githubusercontent.com/7027319/56870018-af978d80-6a00-11e9-9e28-92189e99cd57.png)

**Comment by NicoHood** [comment]
Are you sure this is an issue of the arc theme? Does it also happen in other themes?

**Comment by medmedin2014** [comment]
It happens with other themes (except for built in themes), I asked on Ubuntu Mate forum and they given me solution [fix-caja-foreground-color-in-dual-pane](https://ubuntu-mate.community/t/fix-caja-foreground-color-in-dual-pane/19401)
