### ISSUE TITLE
Odd design choice for the Nautilus pathbar

### ISSUE THREAD

**Issue by sagcan** [NicoHood/arc-theme#235]
Hi, first of all a big thank you to everyone involved in keeping the Arc-Theme alive. 

Anyways, the current design choice for the Nautilus pathbar is a bit odd if you'd ask me (background filling without any margins) 
![pathbar_current](https://user-images.githubusercontent.com/29666622/56964379-5db74a80-6b5b-11e9-9820-e2a7f4e84a35.png) especially when comparing it with issue #133 where @jnsh posted the following solution (minus the underlining upon a mouse-hover)
![pathbar_old](https://user-images.githubusercontent.com/39574454/46588910-27758900-caac-11e8-868b-3fdb3adfa3a8.png)
Is there any reason for not choosing the latter one? For comparison here's the Adwaita theme:
![new](https://user-images.githubusercontent.com/29666622/56964980-7e33d480-6b5c-11e9-8b7f-4f5519a4c3e7.png)

**Comment by NicoHood** [comment]
@jnsh maybe you can give more details?

**Comment by sagcan** [comment]
So I applied the following CSS via the GtkInspector
```CSS
.text-button {
	margin: 0px;
	border-radius: 0px;
	transition-duration: 0ms;
}
```
which looks like this:
![image](https://user-images.githubusercontent.com/29666622/57012791-89dcd500-6c08-11e9-9c38-4dec44fbd33f.png)
In my honest opinion the result looks way cleaner / better than what currently is on upstream since it aligns perfectly with every other `image-button` within the `titlebar`. Also I feel like transition are unnecessary within the `path-bar-box` so I disabled them. Any thoughts on this?

**Comment by ccrisan** [comment]
+1

**Comment by jnsh** [comment]
#133 was for Nautilus 3.30.

Nautilus 3.32 changed the path-bar design again, and needs separate styling. I've implemented this for my own repo with these commits: [[1]](https://github.com/jnsh/arc-theme/commit/a2f6aa6e6c4605cb1295678cc304e4d1a03c9486) [[2]](https://github.com/jnsh/arc-theme/commit/09f4ad7f81cc4fa4a94759f53bc57fd1dcb4bfe9) [[3]](https://github.com/jnsh/arc-theme/commit/3ee5849cdb2db299031b5eae00587c86ce1a46ff). I'd imagine you should be able to cherry-pick those without conflicts if you want.

**Comment by NicoHood** [comment]
It looks like you have changed a lot in your fork. Maybe you want to share those other fixes with us? :-)

**Comment by ccrisan** [comment]
I think it's worth considering cherry-picking the commits @jnsh mentioned. I did that myself locally and Nautilus started to look pleasant again. I believe this issue should receive more interest than it does now.

**Comment by jnsh** [comment]
> It looks like you have changed a lot in your fork. Maybe you want to share those other fixes with us?

@NicoHood Frankly, I have lost all motivation for contributing directly to your fork any more.

Naturally there's nothing stopping you from cherry-picking commits from my repo. However I'm not keeping it in sync with yours, so there's no guarantee that any of the commits from my repo would work as intended, or didn't break something else on your fork.

My plan is to keep maintaining and fixing the theme further on my repo. If anyone finds my work beneficial, I do appreciate all testing and bug reports.

**Comment by NicoHood** [comment]
@jnsh What is the reason why you prefer your fork? Wouldnt it be better to work together? You have a lot of knowledge, that could help everyone. I have no problem with adding you as a member to the project, maybe that would give you more flexibility?

**Comment by jnsh** [comment]
@NicoHood See discussion here: https://github.com/NicoHood/arc-theme/commit/a6cf4045f6f59fae91831401f9b3bbcfd72d0916#commitcomment-33569969
