### ISSUE TITLE
GNOME 3.32 Settings CSD bug

### ISSUE THREAD

**Issue by SaucySauce** [NicoHood/arc-theme#238]
The settings app has a small white line in the navigation bar or CSD. It's static, no changes occur with mouse hover or moving the window.
This bug occurs in every GNOME 3.32 Settings app I've tried so far, Ubuntu Budgie 19.04 and Fedora GNOME shell 30.
Both were fresh installs with only package updates done to them and adding and applying this theme.
Both installed from the repos as specified in the Github page.
Currently on: Ubuntu Budgie 19.04

Budgie 10.5
Arc version: 20190213-1
gtk2-engines-murrine version: 0.98.2-2ubuntu1
gnome-themes-standard: 3.28-1ubuntu1
libgtk-3-0: 3.24.8-1ubuntu1
![Screenshot from 2019-05-07 17:21:57](https://user-images.githubusercontent.com/38703177/57319704-bb640d80-70ec-11e9-92d6-12262a23d18b.png)

**Comment by NicoHood** [comment]
I also have this issue. I remember this was reported some (long) time ago already.

**Comment by SaucySauce** [comment]
Can't you fork the code section of the headerbar from an arc based theme or similar?
