### ISSUE TITLE
Gnome Shell display error: transparent top bar

### ISSUE THREAD

**Issue by brainbug89** [NicoHood/arc-theme#239]
The top bar is transparent and you can't read the date/time if you hover your mouse over it (see attached screenshot). I've already tried purge and remove and reinstall via apt.
Disabling all extensions didn't help either.

### Details

- Distribution (with version): Ubuntu 19.04
- Desktop environment (with version):  Gnome 3.32.1
- Arc version/commit (don't put "latest"):
- GTK+ 3 version: 3.24.8-1ubuntu1
  - Murrine engine version:
  - `gnome-themes-extras` version: 3.28-1ubuntu1
- Installation method (package or source): `sudo apt install arc-theme`
- GNOME Shell 3.32.0

![image](https://user-images.githubusercontent.com/21130949/57442714-ce8def00-724c-11e9-90af-9c84d05f5ba3.png)

**Comment by fossfreedom** [comment]
The transparent bar is resolved in the current stable package in my PPA (see the readme) - the version of arc-theme in Ubuntu was before the latest gnome-shell that broke lots of stuff.

Blue obs is a separate issue https://github.com/NicoHood/arc-theme/issues/236
