### ISSUE TITLE
Invisible text cursor issue on renaming folder

### ISSUE THREAD

**Issue by anjari** [NicoHood/arc-theme#253]
I'm using manjaro linux (arch linux) with cinnamon DE (GTK v3.24.8), and Arc-Theme v2019-03-30.

Not sure if this is theme issue or GTK issue, but when renaming a folder (press F2 on a selected folder, then press left/right arrow key to move the cursor), the text cursor has very light grey color that made the cursor looks invisible.

Other theme had similar issue too: https://forums.linuxmint.com/viewtopic.php?t=278728

If this is theme issue, is there a workaround by modifying the css file?

**Comment by smurphos** [comment]
Hi @anjari is this on the desktop or in Nemo? If the former see https://github.com/linuxmint/nemo/issues/2121

**Comment by anjari** [comment]
@smurphos Yes it's on desktop. Thanks, I followed your suggestion [here](https://github.com/linuxmint/nemo/issues/2121#issuecomment-485070730) and the cursor now can be seen.

**Comment by smurphos** [comment]
No worries

@NicoHood @fossfreedom - this can be closed - nothing to do with Arc, just a missing caret-color definition in nemo's  hard-coded mandatory css.
