### ISSUE TITLE
Off-center Show All Applications Button on dash-to-dock

### ISSUE THREAD

**Issue by sockusminimus** [NicoHood/arc-theme#33]
The dash-to-dock "Show All Applications" button is off-center when using this theme with the "shrink the dash" option selected.  It also does not take up the full panel with or without this option selected, which makes it counter-intuitive to click.

![screenshot from 2018-01-10 17-47-50](https://user-images.githubusercontent.com/1087972/34799591-6840e90a-f62e-11e7-9b71-afbac90df370.png)

**Comment by fossfreedom** [comment]
I am not a gnome shell user as such not familiar  with this issue. If any one is would like a suggested fix or pull request to resolve.

**Comment by pauldmartin** [comment]
Awesome.  I propose expanding the button to occupy the almost the entirety of the frame (while retaining a square shape).  If this is acceptable I will submit a patch this weekend.

**Comment by fossfreedom** [comment]
sounds very reasonable to me!

**Comment by sethen** [comment]
Had the same issue -- I fixed this by changing by turning off `Shrink the dash` in `Dash to dock` settings.  This may or may not apply to you though.

**Comment by tista500** [comment]
I've pushed the PR: https://github.com/NicoHood/arc-theme/pull/70

**Comment by NicoHood** [comment]
Is anyone of the affected users willing to test the PR?
