### ISSUE TITLE
Firefox 57.0.1 with CSD on makes window buttons double up

### ISSUE THREAD

**Issue by mymindstorm** [NicoHood/arc-theme#34]
Continuing from: [#862](https://github.com/horst3180/arc-theme/issues/862)

Built off of  42d8f23, issue still persists.

Firefox issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1408335 

Patch author explains cause in comment 6: 

> It's caused by Gtk+ themes with a specific button.titlebutton theming.
>
> For instance Arc-Dark defines:
> 
> .titlebar button.titlebutton.close,
> .titlebar button.titlebutton.maximize,
> .titlebar button.titlebutton.minimize {
>     color: transparent;
>     ....
> }
> 
> .titlebar button.titlebutton.close {
>  background-image: -gtk-scaled(url("assets/titlebutton-close-dark.png"), url("assets/titlebutton-close-dark@2.png")); }
> 
> which means default Gtk+ titlebar button is transparent (invisible) and it's completely replaced by background-image.

**Comment by fossfreedom** [comment]
this one we need to watch - it appears from the comments it is firefox that are actively looking to resolve - seems to be a buggy CSD implementation.

**Comment by ArchangeGabriel** [comment]
A workaround was proposed here while waiting for the real fix: https://github.com/horst3180/arc-firefox-theme/issues/139#issuecomment-360969481.

**Comment by mymindstorm** [comment]
That fixed the close button, but not the minimize button for me

**Comment by ArchangeGabriel** [comment]
Well the real fix has landed in nightly. I’m correctly having not doubled up buttons right now, and I think the size should be in the next nightly.

**Comment by fossfreedom** [comment]
closing as this is an upstream issue.
