### ISSUE TITLE
[Feature Request] Add variant with no animations/transitions/gradients

### ISSUE THREAD

**Issue by dp-alvarez** [NicoHood/arc-theme#39]
First of all thank you very much for picking up this project, I was afraid Arc would die!

Second, I'd like to know if there is interest to implement a "simpler" variant of Arc that does not use any kind of transitions, animations, gradients, fade effects, transparency, translucency, etc. Basically disable anything that "moves".

It would come handy for low-end computers that would have to render less stuff or for people like me that simply dislike such visual effects.

Right now I use a simple script to remove all references I could find to such things in Arc-solid, but it is very crude and quite possibly breaks stuff. Having upstream support for this would be much better.

**Comment by fossfreedom** [comment]
Attach your script here. Let's have a look to see what is the art of the possible.
Cheers

**Comment by NicoHood** [comment]
You can disable such things in gnome with the tweak tool. Did you try that?

**Comment by NicoHood** [comment]
@dp-alvarez Is this issue still relevant?
