### ISSUE TITLE
Update Readme with information about this fork

### ISSUE THREAD

**Issue by NicoHood** [NicoHood/arc-theme#4]
We should add some information why this fork exists and who maintains it. So that people who come here know, that this is the new, semi official upstream.

**Comment by ItamarShDev** [comment]
@fossfreedom so this should be closed now imo :)

**Comment by fossfreedom** [comment]
Indeed!

**Comment by NicoHood** [comment]
@fossfreedom I recently created the following for my projects:
https://www.buymeacoffee.com/nicohood

If you agree we could add it here to. I dont expect great earnings, but people recently asked me more often for such donation links. It would make most sense to add two individual links, if you are interested.

**Comment by fossfreedom** [comment]
To be honest - I'm a little uncomfortable.

I tend to have donation links for projects that I have initiated myself and continue to maintain.  Where I have taken over a project I tend to not add a link.

Arc and similar is really the baby of horst.  As such, if there was a donation link, I would be more comfortable for it to be an opensource organisation or charity.

Anyway - this is just me - feel free to include a coffee link if you wish.
