### ISSUE TITLE
Icons not looking like preview

### ISSUE THREAD

**Issue by sethen** [NicoHood/arc-theme#40]
Looks like my icons are not working properly.  Looking at the preview, my icons on the sidebar are not in black and white and my application launcher hasn't changed.  Here is a screen shot:

![screenshot from 2018-01-14 17-09-50](https://user-images.githubusercontent.com/1493530/34926520-f6091b8e-f97d-11e7-95af-fabe9c661804.png)

As you can see, the icons on the left still have color.  Also, my menu on the top bar doesn't have the three dots either.

How do I fix this?  I thought I did everything right to make this look correct.

### Details

- Distribution (with version):  Manjaro 17.1.1 Hakoila
  - Base distribution (if have, with version):  Arch
- Desktop environment (with version):  Gnome
- Arc version/commit (don't put "latest"):  arc-gtk-theme 20170302-4
- GTK+ 3 version:  gtk3 3.22.26+47+g3a1a7135a2-3
  - Murrine engine version:  gtk-engine-murrine 0.98.2-2.2
  - `gnome-themes-standard` version:  gnome-themes-standard 3.22.3+13+ga993fdc0-1
- Installation method (package or source): yaourt and pacman

**Comment by fossfreedom** [comment]
As far as I can gather the arc icon theme was never finished and as such you have inconsistencies such as this.

Choose a different more established icon theme such as moka or papirus.

This issue isn't a gtk theme  issue as far as I can see.

**Comment by NicoHood** [comment]
> Screenshot Details: Icons: Arc | Launcher Icons based on White Pixel Icons | Wallpaper | Font: Futura Bk bt

You have to add those to your **icon** theme yourself, horst never finished it. https://darkdawg.deviantart.com/art/White-Pixel-Icons-252310560

**Comment by sethen** [comment]
@NicoHood Oh I see... How do I add these to the theme?  Is there any issue or guide out there to help me through that?

**Comment by NicoHood** [comment]
@sethen I have no idea. We are currently trying to keep the gtk theme alive, I hope to do the same for the icon theme. But I have no idea, just read up on gtk icon themes in general.

**Comment by qwertychouskie** [comment]
@sethen I use Papirus-Dark and it looks beautiful with Arc-Dark.

![image](https://user-images.githubusercontent.com/13989090/34956845-ca42254c-f9df-11e7-9f9e-e39fc26e0d73.png)
