### ISSUE TITLE
Firefox Inputs are overly dark

### ISSUE THREAD

**Issue by YoungElPaso** [NicoHood/arc-theme#41]
I believe this is a duplicate from the o.g. repo on github: https://github.com/horst3180/arc-theme/issues/833

Here's the details about system etc: 
Ubuntu 17.10
gnome-shell 3.26.1
arc-theme/artful,artful,now 20171105-0+201801142001~ubuntu17.10.1 all [installed]
gtk 3.22.25-0ubun 
gnome-themes-standard 3.22.3-ubuntu1
installation method, package: ppa:fossfreedom/arc-gtk-theme-daily

Using arc dark I get inputs that look like: 
![screenshot-2018-1-15 input](https://user-images.githubusercontent.com/54349/34962724-f48bc51e-fa12-11e7-8491-c45db2b68f6a.png)
and scrollbars that look like: 
![screenshot-2018-1-15 nicohood arc-theme](https://user-images.githubusercontent.com/54349/34962744-0bc1e93e-fa13-11e7-9608-4a22300acebc.png)

The scrollbars aren't an issue really, but the inputs seem off (i.e. hard to use)

**Comment by ArchangeGabriel** [comment]
This is a… seventeen years old problem in Firefox with dark gtk themes. See https://bugzilla.mozilla.org/show_bug.cgi?id=70315.

**Comment by YoungElPaso** [comment]
@ArchangeGabriel thanks, and wow, that's an old issue!  

Found this:

https://addons.mozilla.org/en-US/firefox/addon/text-contrast-for-dark-themes/?src=api 

Seems to be a work-around people use.
