### ISSUE TITLE
20180114 - gtk-3.0 files seem missing incomplete - theme not working...

### ISSUE THREAD

**Issue by Geyup** [NicoHood/arc-theme#42]
```20171105``` has all the gtk-3.0 files as the original you forked from. 20180114 is broke and seems to be missing files for gtk-3.0, we need an update...

I'm using the gtk 3.18 folder, but I noticed all the gtk-3.0 folders missing files...

I looked inside ```20171105```

Arc/gtk-3.0 >ls
assets  assets.svg  assets.txt  gtk-dark.css  gtk-darker.css  gtk-solid-dark.css  gtk-solid-darker.css  gtk-solid.css  gtk.css  render-assets.sh  sass

The contents of ```20180114```
/home/foo/.themes/Arc/gtk-3.0>ls
assets  assets.svg  assets.txt  render-assets.sh  sass

If I use a system theme as example, Adwaita, then switch to Arc, I see all of my apps that are compiled against gtk3 still using the Adwaita theme, I'm assuming because you are missing the files that ```20171105``` has.

Hmm

**Comment by fossfreedom** [comment]
Hmm. Ok will double check soon.

**Comment by fossfreedom** [comment]
I installed from my daily ubuntu PPA the latest xenial version which is GTK+3.18 - this works just fine with all the necessary files dated Jan 15 in the gtk-3 subfolder

Are you manually compiling and installing?
Did you install the sassc prerequisite which is needed to compile the theme?

**Comment by sla0101** [comment]
I don't compile themes, I manually install them... The theme contents is in the ```common``` directory.

So this is what I've been doing, renaming the ```common``` folder to ```Arc```, then taking out the 3.18 folder and renaming that to gtk-3.0 and deleting all the others, and moving it to the top directory so all the contents are as follows;

```gtk-2.0  gtk-3.0  index.theme  index.theme-dark  index.theme-darker```

As I mentioned ```20171105``` works but ```20180114``` doesn't.

I'm not a theme maker but I have used them for many many years, and every gtk3-0 directory I have looked through has css files and a settings.ini in it, this doesn't.

**Comment by Geyup** [comment]
I don't compile themes, I manually install them... The theme contents is in the ```common``` directory.

I use Slackware and Openbox, so I have no need to compile a theme, never have...

This is what I've been doing, renaming the ```common``` folder to ```Arc```, then taking out the 3.18 folder and renaming that to gtk-3.0 and deleting all the others, and moving it to the top directory so all the contents are as follows;

```gtk-2.0  gtk-3.0  index.theme  index.theme-dark  index.theme-darker```

And copying it to the ```Arc``` directory to my ```/home/user/.themes```

As I mentioned ```20171105``` works but ```20180114``` doesn't, so it's pretty easy to see it's not an issue on my end, otherwise both would not work, as example...

Plus, Cascading Style Sheets is how GTK3 themes works, so I don't even get how a gtk3 could work if they are missing, or how you are even able to get them to work in Ubuntu, with them missing.

**Comment by Geyup** [comment]
Sorry I hope you don't get emailed or messaged with updates or issue reports, because I was stuck a few times getting my thoughts together and edited and deleted my reply several times.

It's clear to see the latest theme is missing the CSS files, which is how a GTK3 theme works...

**Comment by NicoHood** [comment]
You need to compile the css files with sassc. Read the instructions about manual installation. Run configure and make and the css files should appear. They are not autogenerated anymore in order to avoid confusion and wrong PRs, to resolve merge conflicts better and to get rid of gulp.

**Comment by Geyup** [comment]
Could you please put up the theme completed?

After all I mentioned you list 3 archives;

arc-theme-20180114.tar.xz
Source code (zip) 
Source code (tar.gz) 

Source should be for those that wish to compile and arc-theme-20180114.tar.xz should be the completed theme, ready to just copy and install...

No offense meant, but I don't want to compile a theme, or needing to also have a dependency in order to do so...

I appreciate that you are taking over this theme, but asking people to compile to install should not be needed...

Thanks

**Comment by NicoHood** [comment]
That is how software packaging works. You have sources, make- and runtime dependencies. And you've got packagers who package the software. Use the appropriate package for your distribution. As an alternative you can download the archlinux package which is simply a tar with all files + metainformation. This is exactly what you want. You can find it here (click: download from mirror):
https://www.archlinux.org/packages/community/any/arc-gtk-theme/

**Comment by Geyup** [comment]
Of course I know how packaging works I'm a Slackware Geek, been at it a very long time. SO now with that in mind, I'm trying to tell you, that you have your Archives set up wrong.

Why I say wrong? Because you list as I mentioned 2 called source, along with one archive just named for what it is, and when developers do this, the named archive as in this case, ```arc-theme-20180114.tar.xz```, that would be the application, and the others as the source to compile it from.

I opened all 3 archives, every one of them was the same, that's the confusion, they aren't suppose to be this way.

So hopefully in the future you'll change it and offer the completed theme, along with the 2 source archives...

Thanks for your time, it's greatly appreciated, and I do like the work you have been doing. This is my favorite theme...

That theme from Arch won't work for me, Arch uses a newer version of GTK3 then Slackware.

**Comment by NicoHood** [comment]
@fossfreedom what do you think on this issue? Should we provide precompiled themes to put into the user directory. Maybe it is no that bad idea, however -as he mentioned - we need to make sure to support all gtk versions, I am not sure if that gives us trouble in compiling tons of versions.

@Geyup If you are familar with packaging, why dont you offer packages for the slackware community? Would that be an option?

**Comment by Geyup** [comment]
First let me say, THANKS for the happy replies, wasn't sure how you all were going to take this.

Of course I don't know how long either of you have been in Linux, but if long, then you know that going back years, end-users didn't compile themes, the developer had them ready to just copy and paste.

I guess things are getting more complicated...

Of course, when someone wants to go out and download an application, like Openbox, tint2, mpv, deadbeef, etc... All you find on a developers website is source, and if you want the binary, that will typically come from the Maintainer of it on that particular distro...

But we're not talking about an application here, and themes have always come ready, at least that has been the common practice in the past, and you still see it to this day with many theme makers...

So what to do? Hmm

Now as far as me doing something, to be honest, as a Slacker, I'm still somewhat the old thinking, of just downloading a theme and copying it to my $HOME theme /path and be done with it. I've never compiled a theme, so it's really not something I like to mess with, and please don't take that as being rude towards either of you, just my own personal tastes in the matter.

Also, for a lack of words, I'm a picky lightweight geek, I only install what I need, again not trying to be rude here, but I have no need for sassc or libsass, so I would't install it just for a theme.

I guess I'm one of these extreme crazy light weight geeks, I also have a minimal stripped down Slackware installation, only Openbox, everything to the bare bones, that I only need... But of course I do compile most of my apps, themes just happen to be something I don't...

On last thing, maybe my thinking is wrong here, problem is, I'm not a coder, I'm more the hardware/admin type of geek, and I never thought something like a theme needs compiling, that this is just code like xml, php, css, html, etc... code that all you do is simply hand write it out to make, and of course graphics created in like Gimp, inkscape... So this compiling, I don't get where the 'Aspect of Compiling' comes into play and why it's needed for an end-user...  Hmm

Thanks

**Comment by NicoHood** [comment]
The compiling is used to make things simpler for multiple variants, to change colors real quick (we made the text colors darker with very small changes, and less mistakes).

Try to extract the debian or ubuntu package then. It should have all you need precompiled, if the arch package does not work. Otherwise contact your slackware team to add it as official package.

**Comment by Geyup** [comment]
Well Slackers, you're not going to find many of them, if any, compiling themes, because this is not a common thing yet.

Ubuntu seems to be using Horst's and I'm not seeing anything completed online to download for Debian, just the source, maybe I didn't look hard enough...

Sorry to much effort for a theme... :(
