### ISSUE TITLE
 oomox compatibility request for arc theme

### ISSUE THREAD

**Issue by geplus** [NicoHood/arc-theme#45]
Hi,
This feature request was already done to @horst3180 , so I report it on your issue board.
I think this could be very useful for people that would customize the arc theme in a simple way.
https://github.com/horst3180/arc-theme/issues/816

**Comment by NicoHood** [comment]
@actionless could you please give us more details what this oomox would do for arc and what we need to change?

**Comment by actionless** [comment]
basically see those PRs which i made for Materia:

https://github.com/nana-4/materia-theme/pull/133/files (just basic color substitution with `sed` + re-generating all the assets from SVG, where colors where already replaced as text, to PNG)

https://github.com/nana-4/materia-theme/pull/211/files (using template for scss, opional)

**Comment by actionless** [comment]
i see you also have a script for rendering assets so it should be quite the same as for Materia theme

**Comment by actionless** [comment]
a small teaser...

![2018-08-04--1533361114_1920x1080_scrot](https://user-images.githubusercontent.com/1655669/43672929-738a3ba4-97b9-11e8-9841-5773ce148da1.png)

**Comment by actionless** [comment]
the problems so far:
1) changing button bg/fg is not possible (in gtk3 it's computed from bg, in gtk2 it's the same as text entry)
2) fg and text entry fg are the same; that means what theme with dark bg and light text entry bg will be not readable

**Comment by actionless** [comment]
today had a chance to play a bit more with it and now it feels mostly done, gonna submit a PR tonight unless some unexpected glitches will show up
