### ISSUE TITLE
Color top bar gnome

### ISSUE THREAD

**Issue by fpafumi** [NicoHood/arc-theme#46]
https://github.com/horst3180/arc-theme/issues/867

![](https://user-images.githubusercontent.com/18738278/35216143-e5c29888-ff66-11e7-943d-097cec74a009.png)

Debian buster and gnome Version 3.26.2

top bar is dark and date text is dark too

![](https://user-images.githubusercontent.com/18738278/35215480-ad4f7748-ff64-11e7-8bc6-ab69dd9c545f.png)

**Comment by NicoHood** [comment]
Fixed in #47 
Thanks for the support!
