### ISSUE TITLE
Request: gnome-terminal with a solid design.

### ISSUE THREAD

**Issue by Tids** [NicoHood/arc-theme#48]
could you change the gnome terminal to always use the theme border color as background + add a minimal padding

```
VteTerminal, vte-terminal {
        padding: .5em;
        background-color: #2F343F;
}
```
^ for the dark version, since I enforce dark themes on terminal.

![image](https://user-images.githubusercontent.com/18744080/35290079-66453fda-0069-11e8-94f8-b383fb6dcacc.png)

compared to default:

![image](https://user-images.githubusercontent.com/18744080/35290170-ac103df8-0069-11e8-966a-4a258c016f97.png)

Many people already use it like this, so I think its a not so bad idea to have it by default.

**Comment by NicoHood** [comment]
I personally do not like it. I also use the dark theme and think it is good, as it is. Please explain us how many "many" people are. Who?

**Comment by Aaahh** [comment]
I'm a fan but with transparency this does not look as good

**Comment by NicoHood** [comment]
Thanks for your suggestion. As mentioned we will not apply the change, but you can customize your own arc fork :)
