### ISSUE TITLE
shadow issue

### ISSUE THREAD

**Issue by linusheinz** [NicoHood/arc-theme#49]
I use GNOME 3.26 on arch and the arc theme . i have an issue with a wierd shadows arround the sound icon, this appears also around notifications 
![screenshot from 2018-01-23 17-15-11](https://user-images.githubusercontent.com/20044115/35294293-794c4e18-0076-11e8-85a3-5d8089f4aeb7.png)

**Comment by fossfreedom** [comment]
A pull request to fix would be most welcome

**Comment by NicoHood** [comment]
I have the same setup and I do not see this issue. Which version of the theme are you using? Does it also appear with other themes?

**Comment by linusheinz** [comment]
Strange :/ I build the theme directly from this repo today because i thought it would resolve the issue . I tried with the materia theme and there were no artifacts . I use the papirus icon theme but for testing reasons, i switched back to adwaita but the shadow still persisted

**Comment by tista500** [comment]
Greetings,

I'm not sure but I don't think this was the Arc issue.
If you guys had overridden the system-wide `gresource` file placed at `/usr/share/gnome-shell/`, you should revert it to stock Adwaita's gresource file whenever switching user-themes. That gresource file has the highest priority for gnome-shell, means gnome-shell overrides user-theme's CSS with that gresource file.

Regards.

**Comment by linusheinz** [comment]
Thank you !! i replaced this file for a custom gdm theme after changing it back the issue went away. My fault . But thank you all for your kind help.

**Comment by SolarLiner** [comment]
If anybody has this issue in Ubuntu 18.04, install the package `vanilla-gnome-desktop` and on the next login, select "GNOME" or "GNOME on Xorg". Those profiles do not have the Ubuntu modified CSS for the GNOME Shell.

If you want the Ubuntu login screen back, simply enter `sudo update-alternatives --config gdm3.css` and select the CSS file from the Yaru theme (in the Yaru folder).

**Comment by benjaminreichDE** [comment]
I open a ubuntu bug report for it. https://bugs.launchpad.net/ubuntu/+source/gnome-shell-extension-ubuntu-dock/+bug/1769383

**Comment by abdl-dev** [comment]
I also have never changed `gresource`. Part of the issue is that it is difficult to reproduce. I had the exact same issue as above, on both my desktop and my laptop (with nearly identical setups). On both, after flipping between `Arc` and `Arc-Dark`  for the shell setting in `gnome-tweaks`, and going in and out of the gnome activities screen a few times, the issue resolved itself. However, it reappears on reboot without fail. 

It seems unlikely that it is due to a user modification because of the (seemingly) arbitrary nature of the bug.
