### ISSUE TITLE
Set up a PPA for this fork

### ISSUE THREAD

**Issue by i2000s** [NicoHood/arc-theme#5]
As Horst3180's [PPA is no longer working](https://github.com/horst3180/arc-theme/issues/793#issuecomment-346429922), I would appreciate it if someone can set up a PPA for this fork. I have tried to debianize it up but couldn't pass through the `debuild -S` step to generate the source ball before uploading to Launchpad. Any pointers will also be helpful if no one wants to maintain the PPA.

**Comment by fossfreedom** [comment]
yeah - I'll do that.

To make a PPA viable, we need help with fixes etc to the theme - so feel free to help out if you can ... or cajole other fellow arc enthusiasts to submit PRs

**Comment by i2000s** [comment]
Thanks. I have forwarded this fork to related people.

**Comment by fossfreedom** [comment]
@i2000s hopefully from tomorrow all changes will be captured via this PPA for all supported distro series

https://launchpad.net/~fossfreedom/+archive/ubuntu/arc-gtk-theme-daily

**Comment by i2000s** [comment]
That works for me. I'll update the README file with the new PPA shortly.
