### ISSUE TITLE
[XFCE] Thick Border Line At The Bottom Of Windows

### ISSUE THREAD

**Issue by lunix4all** [NicoHood/arc-theme#56]
The window border line at the bottom is considerably thicker than the borders on the left and the right.

You can fix this by resizing the bottom*.png in arc-theme/common/xfwm4/assets/

Some people say that this would impact usability, but this post explains why we should shrink the bottom border: [https://xubuntu.org/news/window-resizing-in-xubuntu-and-xfce](https://xubuntu.org/news/window-resizing-in-xubuntu-and-xfce)

**Comment by fossfreedom** [comment]
Please can you do a pull request with both before and after screenshots?  TIA

**Comment by lunix4all** [comment]
Here's the issue from the original Arc github:

https://github.com/horst3180/arc-theme/issues/780
