### ISSUE TITLE
Default Arc theme does not work well with XFCE4 panel (Arch Linux)

### ISSUE THREAD

**Issue by ovalseven8** [NicoHood/arc-theme#57]
In the XFCE4 panel all the open windows have that white background color what makes it very hard to read the text and also does not look well overall.

![bildschirmfoto_2018-02-17_15-05-40](https://user-images.githubusercontent.com/8258609/36341947-5dd2345c-13f6-11e8-9172-f426b453b976.png)

Unfortunately, I do not know how to fix this. Is this a bug in the Arc theme?

I did not do any modifications etc. I've just installed the ` arc-gtk-theme` package.

### Details

OS: Arch Linux
DE: XFCE4
WM: Xfwm4
WM Theme: Arc-Dark
GTK Theme: Arc [GTK2]
Icon Theme: Papirus

**Comment by waterlubber** [comment]
I actually have a similar issue in MATE with the panel icons. It only happens on some theme variants too (such as Darker)

**Comment by dignityinside** [comment]
Have the same problem with "Arch Solid" theme in xfce4 on ArchLinux.

**Comment by KlaasYK** [comment]
I had the same issue where the open window buttons were white on XFCE.
Installing the `gtk-engine-murrine` package fixed the problem.

I do remember seeing something like:
`(xfwm4:7045): Gtk-WARNING **: 15:13:50.809: Unable to locate theme engine in module_path: "murrine",`
in my `~/.xsession-errors` file.

**Comment by ovalseven8** [comment]
Thanks, I've installed `gtk-engine-murrine` and it's fixed! :)

**Comment by ovalseven8** [comment]
@NicoHood is the maintainer of the arch package -> https://www.archlinux.org/packages/community/any/arc-gtk-theme/

So he should add it as dependency. :)
