### ISSUE TITLE
Question: Are you planning to add an updated fedora repository for the theme soon?

### ISSUE THREAD

**Issue by gsag** [NicoHood/arc-theme#58]
Hi guys, I appreciate a lot the work you're doing on maintaining the arc-theme.
I have a question: Are you planning to add an updated fedora repository for the theme soon?

**Comment by fossfreedom** [comment]
We prefer to have dedicated maintainers for each distro who can verify and ensure that the package and contents work.

**Comment by gsag** [comment]
Sure, I understand. 
Keep doing the great work. ;)
