### ISSUE TITLE
Atom have letter issues with arc themes (ubuntu 18.04)

### ISSUE THREAD

**Issue by buaguiar** [NicoHood/arc-theme#59]
letters are 'disconfigured' (messed up) on atom. Please, need to fix.
![screenshot from 2018-03-10 11 59 16](https://user-images.githubusercontent.com/16211603/37242348-ed8736f0-245f-11e8-9cfd-ff058324925e.png)

**Comment by fossfreedom** [comment]
Can you confirm whether other GTK  themes work or is this specific to arc. Need to determine if this is an arc issue or an atom issue.

**Comment by NicoHood** [comment]
I am using atom 1.24.0 on Arch Linux with gnome and I dont see this issue. Please do what @fossfreedom suggested and tell us the atom version you are using. Also note that ubuntu 18.04 is currently not yet in release state.

**Comment by ptrxyz** [comment]
Could it be that you are using the infinality freetype patchset? I had that issue solved by removing that.

**Comment by buaguiar** [comment]
Hey! It is because of Atom version... I installed Atom beta and resolved the problem! I think atom have problems with ubuntu new behavior. Thanks!
.

**Comment by fossfreedom** [comment]
Cheers for the info. Much appreciated.
