### ISSUE TITLE
Workspace Switcher unreadable on Budgie

### ISSUE THREAD

**Issue by taaem** [NicoHood/arc-theme#60]
The Workspace Switcher on Budgie has in the Light and Darker variants a white background on a dark panel, which leads to very weird styling in my opinion and makes the text, if there are more than 2 applications on that workspace open, unreadable:

![bildschirmaufnahme vom 2018-03-15 13 10 27](https://user-images.githubusercontent.com/7108647/37484612-ca41779e-2867-11e8-9d17-ffeb1ac27d3b.png)
### Details

- Distribution (with version): Solus 3.99
- Desktop environment (with version): latest Budgie
- Arc version/commit (don't put "latest"): 20180114
- GTK+ 3 version: 3.22.28
  - Murrine engine version: 0.98.2,
  - `gnome-themes-standard` version: 3.22.3
- Installation method (package or source): package

**Comment by fossfreedom** [comment]
Pull requests to resolve are always welcome
