### ISSUE TITLE
Chromium titlebar button.

### ISSUE THREAD

**Issue by my30sat** [NicoHood/arc-theme#62]
After last update, Chromium, big titlebar button. In settings "use system titlebar and border" - disabled.

Gnome 3.26.2 (Manjaro)
In others themes (like a Adwaita, Numix) I don't see this.

> Again: Please close this issue and test the newer fork. I think we fixed such an issue already. If it still exists please open a new one there.
https://github.com/NicoHood/arc-theme

Same too problem.
![image](https://user-images.githubusercontent.com/29095597/37988003-738c0950-3208-11e8-8158-8fd2be3dfdc0.png)

**Comment by NicoHood** [comment]
I have the same issue, I guess its another chrome bug. It appeared in the past and got fixed. I guess we have to wait?! The question is why its fixed in numix?!

**Comment by tista500** [comment]
Check my PR please. I did test that PR with Gtk+ 3.22.29 and Chromium 66.0.3359.26 only...

**Comment by fossfreedom** [comment]
ta - if someone doesnt get to test this on a GTK+3.18 distro such as Ubuntu 16.04 I will try to test by spinning up a VM.  Please shout if you can test on a real world xenial install please.

**Comment by tista500** [comment]
OK. I've just tested PR with stock Gtk+ 3.18.9 on Xenial. PR should work as you expected...
