### ISSUE TITLE
Exit button looks strange with enabled CSD in Firefox

### ISSUE THREAD

**Issue by Ancovens** [NicoHood/arc-theme#71]
![kepernyokep 2018-04-23 20-22-19](https://user-images.githubusercontent.com/15733609/39145566-6c38f5aa-4734-11e8-8030-5daebe22ca14.png)

It looks fine with the default theme

**Comment by qwertychouskie** [comment]
Probably a dupe of https://github.com/NicoHood/arc-theme/issues/34.

**Comment by ArchangeGabriel** [comment]
@qwertychouskie Somehow, yes. But actually Mozilla fixed it once, then it regressed because they fixed another issue, and finally they found the proper way to have both fixed at the same time. In recent versions it works perfectly well.

**Comment by Ancovens** [comment]
It is solved so yeah :)
