### ISSUE TITLE
arc-darker not working correctly with thunar 1.8?

### ISSUE THREAD

**Issue by macearl** [NicoHood/arc-theme#87]
First off: I'm sorry if this is not the right place for it, as i'm not sure if this is a bug with arc-theme or thunar or maybe neither.

Thunar 1.8 switched from GTK2 to GTK3 which resulted in arc-darker not looking "right" anymore.

This is how it looked up until now (up to Thunar 1.6, i did not build thunar 1.7.2 from source to test it as there is no arch package for it):
![arc-darker_thunar_1 6](https://user-images.githubusercontent.com/1804541/41310607-4150a25a-6e82-11e8-95e1-fd0a83af5f82.png)

and this is how it looks with Thunar 1.8:
![arc-darker_thunar](https://user-images.githubusercontent.com/1804541/41309932-50cab132-6e80-11e8-975b-ea42b62abd08.png)

To see wether there is a problem with GTK3 on my system i installed nautilus (a.k.a GNOME Files) which to my knowledge uses gtk3 and it looks like i expected:
![arc-darker_nautilus](https://user-images.githubusercontent.com/1804541/41309916-454d40ea-6e80-11e8-86ce-f1f74c3c60b8.png)

I don't have any experiencing with debugging something like this to find out whether this is an issue (either with thunar or arc-theme) or maybe an intended change in thunar.

Any hints would be welcome how i could debug this further.

### Details

- Distribution (with version): Arch linux
- Desktop environment (with version): i3
- Arc version/commit (don't put "latest"): arc-gtk-theme 20180114-1 from the community repo of arch linux
(i also installed the arc-gtk-theme-git package from aur, which looked the same)
- GTK+ 3 version: gtk3 3.22.30-1 (extra repository arch linux)
  - Murrine engine version: not installed
  - `gnome-themes-standard` version: not installed
- Installation method (package or source): arch packages

**Comment by fossfreedom** [comment]
Nautilus has specific styling to make it look the way it currently does. So thunar will similarly need css changes.

I don't have access to this new version here ... but I would thought at some point during ubuntu's 18.10 cycle the new version  will appear. 

Hoping someone from the rolling release families will help out sooner to resolve this.

**Comment by ElArtista** [comment]
Its a problem that exists in the theme in general and i'm pretty sure it has to do with the Thunar special theming missing for gtk3 version.

Some screenshots for comparison:
BEFORE:
https://snag.gy/QDLS32.jpg
AFTER:
https://snag.gy/SF1iGN.jpg

The Thunar tweaks like the ones here: https://github.com/NicoHood/arc-theme/blob/7de6f06ffa06fd934badc51207e77a4ca94793c5/common/gtk-2.0/apps.rc#L1 must be ported over to the gtk3 version.

A quick search https://github.com/NicoHood/arc-theme/search?utf8=%E2%9C%93&q=thunar&type= shows all these kind of tweaks that possibly need to be ported.

Unfortunately i have no knowledge of gtk2/3 theming so the only way i could contribute is by testing the changes.

**Comment by andyboeh** [comment]
I just noticed that it works fine in Greybird - there are quite a few customizations regarding Xfce in general and Thunar in particular: 
https://github.com/shimmerproject/Greybird/blob/93ce4be9c2a9477daab376c8f76afcc6513d9467/gtk-3.0/gtk-contained.css#L4533

I copied the few lines with the top border to my Arc-Darker theme and it worked fine. Unfortunately, I don't have the resources to complete it, but IMHO Greybird's CSS selectors could be used as guide here.

**Comment by fossfreedom** [comment]
Just found out that on Ubuntu, the xubuntu team have the latest thunar in their experimental PPA https://launchpad.net/~xubuntu-dev/+archive/ubuntu/experimental?field.series_filter=bionic

So if you are a xubuntu user you can also investigate and help out as well!

**Comment by ElArtista** [comment]
Fix only applies to Arc-Darker but not to Arc as it previously was and should apply.

**Comment by ElArtista** [comment]
Fix is also incomplete in other ways. The details list does not have the proper row by row color alternation AND the top toolbar is white, and does not match the theme's colors. The Arc-Darker differences for gtk-2.0 and gtk-3.0 thunar can be seen in the below screenshots:

BEFORE:
![image](https://user-images.githubusercontent.com/4622346/42140371-43f94e2e-7da7-11e8-9135-7e36f8d40dd7.png)

AFTER:
![image](https://user-images.githubusercontent.com/4622346/42140376-5384763e-7da7-11e8-95b7-7a17755bad87.png)

I think that the current issue should reopen until all the necessary modifications are complete.

**Comment by Kirpal** [comment]
The fix should apply to Arc (light) too?

**Comment by Kirpal** [comment]
Updated all except the alternating colors:
* Arc
![image](https://user-images.githubusercontent.com/18384371/42176155-004147aa-7df6-11e8-89a4-758acdf6a1bd.png)
* Arc-dark
![image](https://user-images.githubusercontent.com/18384371/42176184-15a1514e-7df6-11e8-8779-654e30546cbc.png)
* Arc-darker
![image](https://user-images.githubusercontent.com/18384371/42176199-255c15f6-7df6-11e8-9c88-dc240df8320d.png)

**Comment by Kirpal** [comment]
I agree that the alternating colors look too busy and out of place with arc

**Comment by macearl** [comment]
I personally don't mind the clean white look, in fact i would actually prefer it to the alternating colors.

But i also almost always use the "View as Icons" option

@Kirpal could you push your changes? I would like to give them a try, from the screenshots it pretty much looks exactly like i would expect arc to look ;)

**Comment by Kirpal** [comment]
I use the icons too. I'll push the changes as soon as I can, I'm at work now.

**Comment by ElArtista** [comment]
As an Arc Light user, i prefer the dark toolbar in the light theme as it was. I've worked with the currently full white version of the theme for about a week and it makes focusing on the directory contents harder due to the missing contrast that the left toolbar provided, so i think that the dark toolbar should exist in the light version too.

**Comment by Kirpal** [comment]
@ElArtista It looks weird to me, having the dark toolbar with the light title bar and app menu...

@macearl Please see my pull request

**Comment by fossfreedom** [comment]
This has been merged. For those interested please try out the changes for each theme variant

**Comment by ElArtista** [comment]
Nice, the menubar with the top toolbar now blend in together again nicely. The alternating colors in the details list are still missing though.

@Kirpal the dark left toolbar with the light left toolbar looked bad when the top toolbar was not blending with the menubar and they both had the bright white color. With the latest changes, if the hinting in the details is also implemented again, it will show nicely again.

Screenshot from before and after gtk-3.0 migration for further comparison:

Before:
![image](https://user-images.githubusercontent.com/4622346/41338110-dc5f3c8a-6ef9-11e8-9a33-b74075cac96d.png)

After:
![image](https://user-images.githubusercontent.com/4622346/42215609-aaa6a628-7ec7-11e8-939a-1ec9302a2fad.png)

**Comment by Kirpal** [comment]
Ohhh I get it now, I thought you meant also having the top toolbar dark, like in arc-darker. Does this look good?
![image](https://user-images.githubusercontent.com/18384371/42220790-0c6ce202-7e9e-11e8-8c9a-773802f4a669.png)

**Comment by ElArtista** [comment]
Oh yes much better!!! If you also add the alternating colors in the details it will be perfect!

**Comment by NicoHood** [comment]
Those bugs are all fixed now? Can I close this issue? The next release on sunday will include those fixes.

**Comment by fossfreedom** [comment]
Think we agree that the alternating colours are  not needed. So therefore I would close this issue.
