### ISSUE TITLE
Distorted icons on Gnome shell bar

### ISSUE THREAD

**Issue by dwma** [NicoHood/arc-theme#95]
### Details

- Distribution (with version): Arch Linux
- Desktop environment (with version): Gnome 3.28
- Arc version/commit (don't put "latest"): 20180114-1
- GTK+ 3 version: 3.22.30-1
- Installation method (package or source): package

Icons on the app menu appear distorted and blurry. I tried the Adwaita icon theme and the Papirus theme to the same effect.

![screenshot from 2018-07-12 16-46-46](https://user-images.githubusercontent.com/14095540/42655888-d1cecd7e-85f3-11e8-9aa1-b140399c4fb3.png)

**Comment by NicoHood** [comment]
Please test with the latest release.

**Comment by dwma** [comment]
Thanks! I updated the package and now this problem is fixed.
