### ISSUE TITLE
Will not build on 18.10 Cosmic (GNOME 3.24)

### ISSUE THREAD

**Issue by fossfreedom** [NicoHood/arc-theme#99]
tracking bug 

build fails on ubuntu 18.10 cosmic - https://launchpadlibrarian.net/379724012/buildlog_ubuntu-cosmic-amd64.arc-theme_20180114-1+201807231401~ubuntu18.10.1_BUILDING.txt.gz

key build error: configure:2889: error: Invalid GNOME version: 3.24

**Comment by tista500** [comment]
I've pushed the PR: https://github.com/tista500/arc-theme/commit/1376676e32593046b942bd79cf7a0199eb6ec18b
